.TH "JMovies.IMDb.Entities.Movies.Production" 3 "Fri Feb 14 2020" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.Movies.Production \- Base class of any production  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBJMovies\&.IMDb\&.Entities\&.Movies\&.Movie\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "long \fBID\fP\fC [get, set]\fP"
.br
.RI "Primary key of a production "
.ti -1c
.RI "long \fBIMDbID\fP\fC [get, set]\fP"
.br
.RI "\fBIMDb\fP ID of the production "
.ti -1c
.RI "string \fBTitle\fP\fC [get, set]\fP"
.br
.RI "Title of the production "
.ti -1c
.RI "int \fBYear\fP\fC [get, set]\fP"
.br
.RI "\fBProduction\fP Year "
.ti -1c
.RI "virtual \fBRating\fP \fBRating\fP\fC [get, set]\fP"
.br
.RI "Current \fBRating\fP of the production "
.ti -1c
.RI "virtual \fBImage\fP \fBPoster\fP\fC [get, set]\fP"
.br
.RI "Poster of the production "
.ti -1c
.RI "long? \fBPosterID\fP\fC [get, set]\fP"
.br
.RI "Reference field for the Poster "
.ti -1c
.RI "virtual ICollection< \fBImage\fP > \fBMediaImages\fP\fC [get, set]\fP"
.br
.RI "Media images related with the production "
.ti -1c
.RI "virtual \fBProductionTypeEnum\fP \fBProductionType\fP\fC [get, set]\fP"
.br
.RI "Type of the \fBProduction\fP "
.in -1c
.SH "Detailed Description"
.PP 
Base class of any production 


.SH "Property Documentation"
.PP 
.SS "long JMovies\&.IMDb\&.Entities\&.Movies\&.Production\&.ID\fC [get]\fP, \fC [set]\fP"

.PP
Primary key of a production 
.SS "long JMovies\&.IMDb\&.Entities\&.Movies\&.Production\&.IMDbID\fC [get]\fP, \fC [set]\fP"

.PP
\fBIMDb\fP ID of the production 
.SS "virtual ICollection<\fBImage\fP> JMovies\&.IMDb\&.Entities\&.Movies\&.Production\&.MediaImages\fC [get]\fP, \fC [set]\fP"

.PP
Media images related with the production 
.SS "virtual \fBImage\fP JMovies\&.IMDb\&.Entities\&.Movies\&.Production\&.Poster\fC [get]\fP, \fC [set]\fP"

.PP
Poster of the production 
.SS "long? JMovies\&.IMDb\&.Entities\&.Movies\&.Production\&.PosterID\fC [get]\fP, \fC [set]\fP"

.PP
Reference field for the Poster 
.SS "virtual \fBProductionTypeEnum\fP JMovies\&.IMDb\&.Entities\&.Movies\&.Production\&.ProductionType\fC [get]\fP, \fC [set]\fP"

.PP
Type of the \fBProduction\fP 
.SS "virtual \fBRating\fP JMovies\&.IMDb\&.Entities\&.Movies\&.Production\&.Rating\fC [get]\fP, \fC [set]\fP"

.PP
Current \fBRating\fP of the production 
.SS "string JMovies\&.IMDb\&.Entities\&.Movies\&.Production\&.Title\fC [get]\fP, \fC [set]\fP"

.PP
Title of the production 
.SS "int JMovies\&.IMDb\&.Entities\&.Movies\&.Production\&.Year\fC [get]\fP, \fC [set]\fP"

.PP
\fBProduction\fP Year 

.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
