.TH "JMovies.IMDb.Entities.PrivateAPI.DisplayablePropertyValue" 3 "Tue Feb 14 2023" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.PrivateAPI.DisplayablePropertyValue \- Class Definition of a private Displayable Property Value\&.  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBPlainText\fP\fC [get, set]\fP"
.br
.RI "Plain Text Value of a displayable property\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class Definition of a private Displayable Property Value\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
