.TH "JMovies.IMDb.Providers.IMDbScraperDataProvider" 3 "Thu Jul 28 2022" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Providers.IMDbScraperDataProvider \- Data provider that fetches the data real-time on \fBIMDb\fP website using Screen Scraping and returns it as per defined in IIMDbDataProvider\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBJMovies\&.IMDb\&.Entities\&.Interfaces\&.IIMDbDataProvider\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Task< \fBProduction\fP > \fBGetProductionAsync\fP (long id, \fBProductionDataFetchSettings\fP settings)"
.br
.RI "Gets Production Information iresspective of type "
.ti -1c
.RI "async Task< \fBPerson\fP > \fBGetPersonAsync\fP (long id, \fBPersonDataFetchSettings\fP settings)"
.br
.RI "Gets Person information "
.ti -1c
.RI "Task< \fBPerson\fP > \fBAsyncGetPerson\fP (long id, \fBPerson\fP person, \fBPersonDataFetchSettings\fP settings)"
.br
.ti -1c
.RI "async Task< \fBMovie\fP > \fBGetMovieAsync\fP (long id, \fBProductionDataFetchSettings\fP settings)"
.br
.RI "Gets Movie information "
.ti -1c
.RI "async Task< \fBTVSeries\fP > \fBGetTvSeriesAsync\fP (long id, \fBProductionDataFetchSettings\fP settings)"
.br
.RI "Gets TV Series information "
.ti -1c
.RI "async Task< \fBProduction\fP > \fBGetProductionAsync\fP (long id)"
.br
.RI "Gets Production Information iresspective of type using the default settings "
.ti -1c
.RI "async Task< \fBMovie\fP > \fBGetMovieAsync\fP (long id)"
.br
.RI "Gets Movie information using the default settings "
.ti -1c
.RI "async Task< \fBTVSeries\fP > \fBGetTvSeriesAsync\fP (long id)"
.br
.RI "Gets TV Series information using the default settings "
.ti -1c
.RI "async Task< \fBPerson\fP > \fBGetPersonAsync\fP (long id)"
.br
.RI "Gets Person information using the default settings "
.ti -1c
.RI "\fBProduction\fP \fBGetProduction\fP (long id)"
.br
.RI "Gets Production Information iresspective of type using the default settings "
.ti -1c
.RI "\fBMovie\fP \fBGetMovie\fP (long id)"
.br
.RI "Gets Movie information using the default settings "
.ti -1c
.RI "\fBProduction\fP \fBGetProduction\fP (long id, \fBProductionDataFetchSettings\fP settings)"
.br
.RI "Gets Production Information iresspective of type "
.ti -1c
.RI "\fBMovie\fP \fBGetMovie\fP (long id, \fBProductionDataFetchSettings\fP settings)"
.br
.RI "Gets Movie information "
.ti -1c
.RI "\fBTVSeries\fP \fBGetTvSeries\fP (long id, \fBProductionDataFetchSettings\fP settings)"
.br
.RI "Gets TV Series information "
.ti -1c
.RI "\fBPerson\fP \fBGetPerson\fP (long id, \fBPersonDataFetchSettings\fP settings)"
.br
.RI "Gets Person information "
.ti -1c
.RI "\fBPerson\fP \fBGetPerson\fP (long id)"
.br
.RI "Gets Person information using the default settings "
.in -1c
.SH "Detailed Description"
.PP 
Data provider that fetches the data real-time on \fBIMDb\fP website using Screen Scraping and returns it as per defined in IIMDbDataProvider\&. 



.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
