.TH "JMovies.IMDb.Helpers.IMDBIDHelper" 3 "Sat Dec 7 2019" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Helpers.IMDBIDHelper \- Class responsible for providing utility methods related to IMDB ID related operations  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static ? long \fBGetIDFromUrl\fP (string url)"
.br
.RI "Method responsible for getting \fBIMDb\fP ID from a URL "
.in -1c
.SH "Detailed Description"
.PP 
Class responsible for providing utility methods related to IMDB ID related operations 


.SH "Member Function Documentation"
.PP 
.SS "static ? long JMovies\&.IMDb\&.Helpers\&.IMDBIDHelper\&.GetIDFromUrl (string url)\fC [static]\fP"

.PP
Method responsible for getting \fBIMDb\fP ID from a URL 
.PP
\fBParameters\fP
.RS 4
\fIurl\fP URL to be parsed
.RE
.PP
\fBReturns\fP
.RS 4
Detected \fBIMDb\fP ID
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
