.TH "JMovies.IMDb.Entities.Settings.Presets.BasicProductionDataFetchSettings" 3 "Sun Sep 15 2019" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.Settings.Presets.BasicProductionDataFetchSettings \- A preset of settings to fetch only basic production data  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBJMovies\&.IMDb\&.Entities\&.Settings\&.ProductionDataFetchSettings\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBFetchDetailedCast\fP\fC [get]\fP"
.br
.RI "Do not fetch detailed cast "
.ti -1c
.RI "override bool \fBFetchImageContents\fP\fC [get]\fP"
.br
.RI "Do not fetch image contents "
.ti -1c
.RI "override int \fBMediaImagesFetchCount\fP\fC [get]\fP"
.br
.RI "Do not fetch media images "
.in -1c
.SH "Detailed Description"
.PP 
A preset of settings to fetch only basic production data 


.SH "Property Documentation"
.PP 
.SS "override bool JMovies\&.IMDb\&.Entities\&.Settings\&.Presets\&.BasicProductionDataFetchSettings\&.FetchDetailedCast\fC [get]\fP"

.PP
Do not fetch detailed cast 
.SS "override bool JMovies\&.IMDb\&.Entities\&.Settings\&.Presets\&.BasicProductionDataFetchSettings\&.FetchImageContents\fC [get]\fP"

.PP
Do not fetch image contents 
.SS "override int JMovies\&.IMDb\&.Entities\&.Settings\&.Presets\&.BasicProductionDataFetchSettings\&.MediaImagesFetchCount\fC [get]\fP"

.PP
Do not fetch media images 

.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
