.TH "JMovies.IMDb.Entities.Common.Image" 3 "Sun Nov 3 2019" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.Common.Image \- Class definition for basic online image  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "long \fBID\fP\fC [get, set]\fP"
.br
.RI "Primary Key "
.ti -1c
.RI "string \fBTitle\fP\fC [get, set]\fP"
.br
.RI "Title of the image "
.ti -1c
.RI "string \fBURL\fP\fC [get, set]\fP"
.br
.RI "URL of the image "
.ti -1c
.RI "byte[] \fBContent\fP\fC [get, set]\fP"
.br
.RI "Content of the image "
.ti -1c
.RI "long \fBPersonID\fP\fC [get, set]\fP"
.br
.RI "Related Person ID "
.ti -1c
.RI "long \fBProductionID\fP\fC [get, set]\fP"
.br
.RI "Related Production ID "
.in -1c
.SH "Detailed Description"
.PP 
Class definition for basic online image 


.SH "Property Documentation"
.PP 
.SS "byte [] JMovies\&.IMDb\&.Entities\&.Common\&.Image\&.Content\fC [get]\fP, \fC [set]\fP"

.PP
Content of the image 
.SS "long JMovies\&.IMDb\&.Entities\&.Common\&.Image\&.ID\fC [get]\fP, \fC [set]\fP"

.PP
Primary Key 
.SS "long JMovies\&.IMDb\&.Entities\&.Common\&.Image\&.PersonID\fC [get]\fP, \fC [set]\fP"

.PP
Related Person ID 
.SS "long JMovies\&.IMDb\&.Entities\&.Common\&.Image\&.ProductionID\fC [get]\fP, \fC [set]\fP"

.PP
Related Production ID 
.SS "string JMovies\&.IMDb\&.Entities\&.Common\&.Image\&.Title\fC [get]\fP, \fC [set]\fP"

.PP
Title of the image 
.SS "string JMovies\&.IMDb\&.Entities\&.Common\&.Image\&.URL\fC [get]\fP, \fC [set]\fP"

.PP
URL of the image 

.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
