.TH "JMovies.IMDb.Entities.Movies.ActingCredit" 3 "Wed Jul 20 2022" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.Movies.ActingCredit \- Class definition of an Acting \fBCredit\fP  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBJMovies\&.IMDb\&.Entities\&.Movies\&.Credit\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBActingCredit\fP ()"
.br
.RI "Default constructor "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual ICollection< \fBCharacter\fP > \fBCharacters\fP\fC [get, set]\fP"
.br
.RI "Characters played by the actor/actress "
.in -1c
.SH "Detailed Description"
.PP 
Class definition of an Acting \fBCredit\fP 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "JMovies\&.IMDb\&.Entities\&.Movies\&.ActingCredit\&.ActingCredit ()"

.PP
Default constructor 
.SH "Property Documentation"
.PP 
.SS "virtual ICollection<\fBCharacter\fP> JMovies\&.IMDb\&.Entities\&.Movies\&.ActingCredit\&.Characters\fC [get]\fP, \fC [set]\fP"

.PP
Characters played by the actor/actress 

.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
