.TH "JMovies.IMDb.Entities.Common" 3 "Thu Jul 28 2022" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.Common
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAmount\fP"
.br
.RI "Class definition of Money related Amounts "
.ti -1c
.RI "class \fBImage\fP"
.br
.RI "Class definition for basic online image "
.ti -1c
.RI "class \fBLength\fP"
.br
.RI "Class definition of \fBLength\fP that contains both Imperial and Metric length information "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
