.TH "JMovies.IMDb.Entities.Interfaces" 3 "Sat Dec 7 2019" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.Interfaces
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBIIMDbDataProvider\fP"
.br
.RI "Data provider interface that Scraper implements\&. This interface can be safely used for Dependency Injection\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
