.TH "JMovies.IMDb.Helpers.Movies.PhotoGalleryPageHelper" 3 "Sun Dec 8 2019" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Helpers.Movies.PhotoGalleryPageHelper \- Class responsible for parsing the Media Images  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBParse\fP (\fBMovie\fP movie, HtmlNode documentNode, \fBProductionDataFetchSettings\fP settings)"
.br
.RI "Main Parse method of the Photo Gallery Page "
.in -1c
.SH "Detailed Description"
.PP 
Class responsible for parsing the Media Images 


.SH "Member Function Documentation"
.PP 
.SS "static void JMovies\&.IMDb\&.Helpers\&.Movies\&.PhotoGalleryPageHelper\&.Parse (\fBMovie\fP movie, HtmlNode documentNode, \fBProductionDataFetchSettings\fP settings)\fC [static]\fP"

.PP
Main Parse method of the Photo Gallery Page 
.PP
\fBParameters\fP
.RS 4
\fImovie\fP Movie instance that is populated
.br
\fIdocumentNode\fP Document Node of the photo gallery page
.br
\fIsettings\fP Object containing Data Fetch settings
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
