.TH "JMovies.IMDb.Helpers" 3 "Fri Feb 14 2020" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Helpers
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBHtmlHelper\fP"
.br
.RI "Class responsible for providing utility methods related to HTML related operations "
.ti -1c
.RI "class \fBHttpHelper\fP"
.br
.RI "Class responsible for providing utility methods for HTTP Operations "
.ti -1c
.RI "class \fBIMDBIDHelper\fP"
.br
.RI "Class responsible for providing utility methods related to IMDB ID related operations "
.ti -1c
.RI "class \fBIMDBImageHelper\fP"
.br
.RI "Class responsible for providing utility methods related to Image related operations for \fBIMDb\fP "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
