.TH "JMovies.IMDb.Helpers.People" 3 "Sun Nov 3 2019" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Helpers.People
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBioPageHelper\fP"
.br
.RI "Class responsible for parsing the Bio Page "
.ti -1c
.RI "class \fBPersonPageHelper\fP"
.br
.RI "Class responsible for parsing the person page "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
