.TH "JMovies.IMDb.Entities.People.ProductionCredit" 3 "Wed Dec 15 2021" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.People.ProductionCredit \- Credit of a person in a specific production  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "long \fBID\fP\fC [get, set]\fP"
.br
.RI "Primary Key "
.ti -1c
.RI "virtual \fBCredit\fP \fBCredit\fP\fC [get, set]\fP"
.br
.RI "Credit "
.ti -1c
.RI "virtual \fBProduction\fP \fBProduction\fP\fC [get, set]\fP"
.br
.RI "The production that person is credited in "
.in -1c
.SH "Detailed Description"
.PP 
Credit of a person in a specific production 


.SH "Property Documentation"
.PP 
.SS "virtual \fBCredit\fP JMovies\&.IMDb\&.Entities\&.People\&.ProductionCredit\&.Credit\fC [get]\fP, \fC [set]\fP"

.PP
Credit 
.SS "long JMovies\&.IMDb\&.Entities\&.People\&.ProductionCredit\&.ID\fC [get]\fP, \fC [set]\fP"

.PP
Primary Key 
.SS "virtual \fBProduction\fP JMovies\&.IMDb\&.Entities\&.People\&.ProductionCredit\&.Production\fC [get]\fP, \fC [set]\fP"

.PP
The production that person is credited in 

.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
