.TH "JMovies.IMDb.Entities.Movies.Credit" 3 "Tue Aug 13 2019" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.Movies.Credit \- Class definition of a credit in a title  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBJMovies\&.IMDb\&.Entities\&.Movies\&.ActingCredit\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBPerson\fP \fBPerson\fP\fC [get, set]\fP"
.br
.RI "Person related to the credit "
.ti -1c
.RI "\fBCreditRoleType\fP \fBRoleType\fP\fC [get, set]\fP"
.br
.RI "Role of the person in the title "
.in -1c
.SH "Detailed Description"
.PP 
Class definition of a credit in a title 


.SH "Property Documentation"
.PP 
.SS "\fBPerson\fP JMovies\&.IMDb\&.Entities\&.Movies\&.Credit\&.Person\fC [get]\fP, \fC [set]\fP"

.PP
Person related to the credit 
.SS "\fBCreditRoleType\fP JMovies\&.IMDb\&.Entities\&.Movies\&.Credit\&.RoleType\fC [get]\fP, \fC [set]\fP"

.PP
Role of the person in the title 

.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
