.TH "JMovies.IMDb.Helpers.Movies.SummaryCastHelper" 3 "Sun Sep 15 2019" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Helpers.Movies.SummaryCastHelper \- Class responsible for parsing Cast Summary Section  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Class responsible for parsing Cast Summary Section 



.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
