.TH "JMovies.IMDb.Entities.Settings.PersonFetchSettingsBuilder" 3 "Sun Feb 26 2023" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.Settings.PersonFetchSettingsBuilder \- Builder for person fetching settings\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPersonFetchSettingsBuilder\fP \fBWithFetchingBioPage\fP ()"
.br
.RI "Enables fetching bio page on the settings\&. "
.ti -1c
.RI "\fBPersonFetchSettingsBuilder\fP \fBWithFetchingImageContents\fP ()"
.br
.RI "Enables fetching image contents fetching on the settings\&. "
.ti -1c
.RI "\fBPersonFetchSettingsBuilder\fP \fBWithLimitedImageFetching\fP (int limit)"
.br
.RI "Sets image fetching limit\&. "
.ti -1c
.RI "\fBPersonFetchSettingsBuilder\fP \fBWithPreferredCulture\fP (string culture)"
.br
.RI "Enables fetching with a preferred culture\&. "
.ti -1c
.RI "\fBPersonFetchSettingsBuilder\fP \fBWithPrivateData\fP ()"
.br
.RI "Enables fetching private data\&. "
.ti -1c
.RI "\fBPersonDataFetchSettings\fP \fBBuild\fP ()"
.br
.RI "Builds a person data fetch settings based on the chained properties\&. "
.in -1c
.SH "Detailed Description"
.PP 
Builder for person fetching settings\&. 
.SH "Member Function Documentation"
.PP 
.SS "\fBPersonDataFetchSettings\fP JMovies\&.IMDb\&.Entities\&.Settings\&.PersonFetchSettingsBuilder\&.Build ()"

.PP
Builds a person data fetch settings based on the chained properties\&. 
.PP
\fBReturns\fP
.RS 4
A built and customized person data fetch settings
.RE
.PP

.SS "\fBPersonFetchSettingsBuilder\fP JMovies\&.IMDb\&.Entities\&.Settings\&.PersonFetchSettingsBuilder\&.WithFetchingBioPage ()"

.PP
Enables fetching bio page on the settings\&. 
.PP
\fBReturns\fP
.RS 4
Builder for more chaining
.RE
.PP

.SS "\fBPersonFetchSettingsBuilder\fP JMovies\&.IMDb\&.Entities\&.Settings\&.PersonFetchSettingsBuilder\&.WithFetchingImageContents ()"

.PP
Enables fetching image contents fetching on the settings\&. 
.PP
\fBReturns\fP
.RS 4
Builder for more chaining
.RE
.PP

.SS "\fBPersonFetchSettingsBuilder\fP JMovies\&.IMDb\&.Entities\&.Settings\&.PersonFetchSettingsBuilder\&.WithLimitedImageFetching (int limit)"

.PP
Sets image fetching limit\&. 
.PP
\fBReturns\fP
.RS 4
Builder for more chaining
.RE
.PP

.SS "\fBPersonFetchSettingsBuilder\fP JMovies\&.IMDb\&.Entities\&.Settings\&.PersonFetchSettingsBuilder\&.WithPreferredCulture (string culture)"

.PP
Enables fetching with a preferred culture\&. 
.PP
\fBReturns\fP
.RS 4
Builder for more chaining
.RE
.PP

.SS "\fBPersonFetchSettingsBuilder\fP JMovies\&.IMDb\&.Entities\&.Settings\&.PersonFetchSettingsBuilder\&.WithPrivateData ()"

.PP
Enables fetching private data\&. 
.PP
\fBReturns\fP
.RS 4
Builder for more chaining
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
