.TH "JMovies.IMDb.Entities.Movies.Character" 3 "Sun Dec 8 2019" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.Movies.Character \- Class definition of a character in a title  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBJMovies\&.IMDb\&.Entities\&.Movies\&.TVCharacter\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "long \fBID\fP\fC [get, set]\fP"
.br
.RI "Primary key of a character "
.ti -1c
.RI "virtual \fBCharacterTypeEnum\fP \fBCharacterType\fP\fC [get, set]\fP"
.br
.RI "Underlining \fBCharacter\fP Type "
.ti -1c
.RI "long? \fBIMDbID\fP\fC [get, set]\fP"
.br
.RI "\fBIMDb\fP ID "
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.RI "Name of the character "
.ti -1c
.RI "long \fBCreditID\fP\fC [get, set]\fP"
.br
.RI "Reference ID of related credit "
.in -1c
.SH "Detailed Description"
.PP 
Class definition of a character in a title 


.SH "Property Documentation"
.PP 
.SS "virtual \fBCharacterTypeEnum\fP JMovies\&.IMDb\&.Entities\&.Movies\&.Character\&.CharacterType\fC [get]\fP, \fC [set]\fP"

.PP
Underlining \fBCharacter\fP Type 
.SS "long JMovies\&.IMDb\&.Entities\&.Movies\&.Character\&.CreditID\fC [get]\fP, \fC [set]\fP"

.PP
Reference ID of related credit 
.SS "long JMovies\&.IMDb\&.Entities\&.Movies\&.Character\&.ID\fC [get]\fP, \fC [set]\fP"

.PP
Primary key of a character 
.SS "long? JMovies\&.IMDb\&.Entities\&.Movies\&.Character\&.IMDbID\fC [get]\fP, \fC [set]\fP"

.PP
\fBIMDb\fP ID 
.SS "string JMovies\&.IMDb\&.Entities\&.Movies\&.Character\&.Name\fC [get]\fP, \fC [set]\fP"

.PP
Name of the character 

.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
