.TH "JMovies.IMDb.Entities.People.Actor" 3 "Tue Aug 13 2019" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.People.Actor \- Class definition of an actor  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBJMovies\&.IMDb\&.Entities\&.People\&.Person\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Class definition of an actor 



.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
