.TH "JMovies.IMDb.Entities.Settings" 3 "Tue Feb 14 2023" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.Settings
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBaseDataFetchSettings\fP"
.br
.RI "Base settings class common to both productions and persons\&. "
.ti -1c
.RI "class \fBPersonDataFetchSettings\fP"
.br
.RI "Class that is responsible for holding settings for Person data fetching\&. "
.ti -1c
.RI "class \fBPersonFetchSettingsBuilder\fP"
.br
.RI "Builder for person fetching settings\&. "
.ti -1c
.RI "class \fBProductionDataFetchSettings\fP"
.br
.RI "Class that is responsible for holding settings for Production data fetching\&. "
.ti -1c
.RI "class \fBProductionFetchSettingsBuilder\fP"
.br
.RI "Class that is responsible for holding settings for Production data fetching\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
