.TH "JMovies.IMDb.Common.Constants.IMDbConstants" 3 "Sun Feb 26 2023" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Common.Constants.IMDbConstants \- Class that holds constant definitions that are related to IMDb\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly int \fBHttpMaxRetryCount\fP = 5"
.br
.RI "Max Retry Count for HTTP Calls\&. "
.ti -1c
.RI "static readonly int \fBHttpRetrySleepTime\fP = 1000"
.br
.RI "Sleep duration in ms to be waited if an exception occurs during Http calls\&. "
.ti -1c
.RI "static readonly int \fBIMDbIDExtendedLength\fP = 8"
.br
.RI "Length of the Extended IMDb IDs\&. "
.ti -1c
.RI "static readonly int \fBIMDbIDLength\fP = 7"
.br
.RI "Length of the IMDb IDs\&. "
.ti -1c
.RI "static readonly string \fBDefaultScrapingCulture\fP = 'en\-US'"
.br
.RI "Default culture to be used while screen scraping\&. "
.ti -1c
.RI "static readonly string \fBBaseURL\fP = 'https://www\&.imdb\&.com/'"
.br
.RI "Base URL of the IMDb website\&. "
.ti -1c
.RI "static readonly string \fBMoviesPath\fP = 'title/'"
.br
.RI "Path of the movies page\&. "
.ti -1c
.RI "static readonly string \fBMovieIDPrefix\fP = 'tt'"
.br
.RI "Prefix of the movie IDs\&. "
.ti -1c
.RI "static readonly string \fBPersonsPath\fP = 'name/'"
.br
.RI "Path of the person page\&. "
.ti -1c
.RI "static readonly string \fBPersonIDPrefix\fP = 'nm'"
.br
.RI "Prefix of the person IDs\&. "
.ti -1c
.RI "static readonly string \fBCharactersPath\fP = 'characters/'"
.br
.RI "Path of the characters page\&. "
.ti -1c
.RI "static readonly string \fBKeywordsPath\fP = 'keyword'"
.br
.RI "Path of the keywords page\&. "
.ti -1c
.RI "static readonly string \fBCompanyIDPrefix\fP = 'co'"
.br
.RI "Prefix of Company IDs\&. "
.ti -1c
.RI "static readonly string \fBCompaniesPath\fP = 'company/'"
.br
.RI "Path of the companies page\&. "
.ti -1c
.RI "static readonly string \fBFullCreditsPath\fP = 'fullcredits/'"
.br
.RI "Path of the Full Credits page\&. "
.ti -1c
.RI "static readonly string \fBReleaseInfoPath\fP = 'releaseinfo/'"
.br
.RI "Path of the Release Info page\&. "
.ti -1c
.RI "static readonly string \fBPhotoGalleryPath\fP = 'mediaindex/'"
.br
.RI "Path of the Photo Gallery Page\&. "
.ti -1c
.RI "static readonly string \fBTVSeriesOgType\fP = 'video\&.tv_show'"
.br
.RI "Type indicator for TV Series\&. "
.ti -1c
.RI "static readonly string \fBBioPagePath\fP = 'bio/'"
.br
.RI "Path of Bio page\&. "
.ti -1c
.RI "static readonly string \fBStar\fP = 'Star'"
.br
.RI "Text of Star title\&. "
.ti -1c
.RI "static readonly string \fBDirector\fP = 'Director'"
.br
.RI "Text of Director title\&. "
.ti -1c
.RI "static readonly string \fBDirectedBy\fP = 'Directed By'"
.br
.RI "Text of Directed by title\&. "
.ti -1c
.RI "static readonly string \fBWriter\fP = 'Writer'"
.br
.RI "Text of Writer title\&. "
.ti -1c
.RI "static readonly string \fBCreator\fP = 'Creator'"
.br
.RI "Text of Creator title\&. "
.ti -1c
.RI "static readonly string \fBTagline\fP = 'Tagline'"
.br
.RI "Text of Taglines title\&. "
.ti -1c
.RI "static readonly string \fBGenre\fP = 'Genre'"
.br
.RI "Text of Genre title\&. "
.ti -1c
.RI "static readonly string \fBOfficialSite\fP = 'Official Site'"
.br
.RI "Text of Official Site title\&. "
.ti -1c
.RI "static readonly string \fBCountryOfOriginFilterName\fP = 'country_of_origin'"
.br
.RI "Filter name of 'Country Of Origin'\&. "
.ti -1c
.RI "static readonly string \fBLanguage\fP = 'Language'"
.br
.RI "Text of Language title\&. "
.ti -1c
.RI "static readonly string \fBPrimaryLanguageFilterName\fP = 'primary_language'"
.br
.RI "Filter name of 'Primary Language'\&. "
.ti -1c
.RI "static readonly string \fBReleaseDate\fP = 'Release Date'"
.br
.RI "Text of Release Date title\&. "
.ti -1c
.RI "static readonly string \fBAKA\fP = 'Also Known As'"
.br
.RI "Text of AKAs title\&. "
.ti -1c
.RI "static readonly string \fBFilmingLocation\fP = 'Filming Location'"
.br
.RI "Text of Filming Location title\&. "
.ti -1c
.RI "static readonly string \fBLocationsFilterName\fP = 'locations'"
.br
.RI "Filter name of 'Locations'\&. "
.ti -1c
.RI "static readonly string \fBBudget\fP = 'Budget'"
.br
.RI "Text of Budget title\&. "
.ti -1c
.RI "static readonly string \fBProductionCompany\fP = 'Production Co'"
.br
.RI "Text of Production Company title\&. "
.ti -1c
.RI "static readonly string \fBRuntime\fP = 'Runtime'"
.br
.RI "Text of Runtime title\&. "
.ti -1c
.RI "const string \fBBioOverviewBirthName\fP = 'Birth Name'"
.br
.RI "Bio Page - Overview Section - Birth Name Title\&. "
.ti -1c
.RI "const string \fBBioOverviewBirthInfo\fP = 'Born'"
.br
.RI "Bio Page - Overview Section - Birth Information Title\&. "
.ti -1c
.RI "const string \fBBioOverviewHeight\fP = 'Height'"
.br
.RI "Bio Page - Overview Section - Height Title\&. "
.ti -1c
.RI "const string \fBBioOverviewNickName\fP = 'Nickname'"
.br
.RI "Bio Page - Overview Section - NickName Title\&. "
.ti -1c
.RI "static readonly string \fBActorCategoryName\fP = 'actor'"
.br
.RI "Actor Filmography Category Name\&. "
.ti -1c
.RI "static readonly string \fBActressCategoryName\fP = 'actress'"
.br
.RI "Actress Filmography Category Name\&. "
.ti -1c
.RI "static readonly string \fBEmptyPlotText\fP = 'Add a plot'"
.br
.RI "Empty text to be checked to determine if there is no plot\&. "
.ti -1c
.RI "static readonly Regex \fBProductionTitleMatcherRegex\fP = new Regex(@'\\/title\\/tt(\\d+)\\/')"
.br
.RI "Regex that matches the title\&. "
.ti -1c
.RI "static readonly Regex \fBStarsSummaryRegex\fP = new Regex(\fBStar\fP + '[s]?:?', RegexOptions\&.IgnoreCase)"
.br
.RI "Regex that matches the stars section in Movie Summary\&. "
.ti -1c
.RI "static readonly Regex \fBDirectorsSummaryRegex\fP = new Regex(\fBDirector\fP + '[s]?:?', RegexOptions\&.IgnoreCase)"
.br
.RI "Regex that matches the directors section in Movie Summary\&. "
.ti -1c
.RI "static readonly Regex \fBWritersSummaryRegex\fP = new Regex(\fBWriter\fP + '[s]?:?', RegexOptions\&.IgnoreCase)"
.br
.RI "Regex that matches the writers section in Movie Summary\&. "
.ti -1c
.RI "static readonly Regex \fBCreatorsSummaryRegex\fP = new Regex(\fBCreator\fP + '[s]?:?', RegexOptions\&.IgnoreCase)"
.br
.RI "Regex that matches the creators section in Movie Summary\&. "
.ti -1c
.RI "static readonly Regex \fBPersonIDURLMatcher\fP = new Regex(Regex\&.Escape(\fBPersonsPath\fP) + \fBPersonIDPrefix\fP + @'(\\d+)', RegexOptions\&.IgnoreCase)"
.br
.RI "Regex that matches the Person ID from URL\&. "
.ti -1c
.RI "static readonly Regex \fBMovieYearRegex\fP = new Regex(@'\\s*(\\d{4})[–\-]?(\\d{4})?\\s*')"
.br
.RI "Regex that matches the movie year in the Movie page\&. "
.ti -1c
.RI "static readonly Regex \fBCharacterRegex\fP = new Regex(\fBCharactersPath\fP + \fBPersonIDPrefix\fP + @'(\\d+)\&.*?')"
.br
.RI "Regex that matches the character IMDb ID\&. "
.ti -1c
.RI "static readonly Regex \fBTaglinesSummaryRegex\fP = new Regex(\fBTagline\fP + '[s]?:?', RegexOptions\&.IgnoreCase)"
.br
.RI "Regex that matches the tag lines section in Movie Summary\&. "
.ti -1c
.RI "static readonly Regex \fBKeywordLinkRegex\fP = new Regex(\fBKeywordsPath\fP + @'[\\/?]{1,2}keywords=(\&.+)&', RegexOptions\&.IgnoreCase)"
.br
.RI "Regex that matches the keywords section in Movie Summary\&. "
.ti -1c
.RI "static readonly Regex \fBGenresSummaryRegex\fP = new Regex(\fBGenre\fP + '[s]?:?', RegexOptions\&.IgnoreCase)"
.br
.RI "Regex that matches the genres section in Movie Summary\&. "
.ti -1c
.RI "static readonly Regex \fBGenreLinkRegex\fP = new Regex(@'title[/\\\\]\\?genres=(\&.+?)[&\\\\'']', RegexOptions\&.IgnoreCase)"
.br
.RI "Regex that matches a specific Genre Link\&. "
.ti -1c
.RI "static readonly Regex \fBOfficialSitesHeaderRegex\fP = new Regex(\fBOfficialSite\fP + '[s]?:?', RegexOptions\&.IgnoreCase)"
.br
.RI "Regex that matches the Official Sites section in Movie Summary\&. "
.ti -1c
.RI "static readonly Regex \fBCountriesHeaderRegex\fP = new Regex('Countr[y]?(ies)?:?', RegexOptions\&.IgnoreCase)"
.br
.RI "Regex that matches the countries section in Movie Summary\&. "
.ti -1c
.RI "static readonly Regex \fBCountryOfOriginRegex\fP = new Regex(\fBCountryOfOriginFilterName\fP + '=(\&.+?)[&\\']', RegexOptions\&.IgnoreCase)"
.br
.RI "Regex that matches the Country Of Origin section in Movie Summary\&. "
.ti -1c
.RI "static readonly Regex \fBLanguagesHeaderRegex\fP = new Regex(\fBLanguage\fP + '[s]?:?', RegexOptions\&.IgnoreCase)"
.br
.RI "Regex that matches the Languages section in Movie Summary\&. "
.ti -1c
.RI "static readonly Regex \fBPrimaryLanguageRegex\fP = new Regex(\fBPrimaryLanguageFilterName\fP + '=(\&.+?)[&\\']', RegexOptions\&.IgnoreCase)"
.br
.RI "Regex that matches the Primary Language section in Movie Summary\&. "
.ti -1c
.RI "static readonly Regex \fBReleaseDateHeaderRegex\fP = new Regex(\fBReleaseDate\fP + '[s]?:?', RegexOptions\&.IgnoreCase)"
.br
.RI "Regex that matches the Release Date section in Movie Summary\&. "
.ti -1c
.RI "static readonly Regex \fBReleaseDateCountryIdentifierRegex\fP = new Regex(@'region=(\&.+?)&', RegexOptions\&.IgnoreCase)"
.br
.RI "Regex that matches the Country Identifier of a Release Date\&. "
.ti -1c
.RI "static readonly Regex \fBAKAHeaderRegex\fP = new Regex(\fBAKA\fP + ':?', RegexOptions\&.IgnoreCase)"
.br
.RI "Regex that matches the AKAs section in Movie Summary\&. "
.ti -1c
.RI "static readonly Regex \fBFilmingLocationsHeaderRegex\fP = new Regex(\fBFilmingLocation\fP + '[s]?:?', RegexOptions\&.IgnoreCase)"
.br
.RI "Regex that matches the filming locations section in Movie Summary\&. "
.ti -1c
.RI "static readonly Regex \fBLocationsLinkRegex\fP = new Regex(\fBLocationsFilterName\fP + '=\&.+\\'>(\&.+)<\\\\/a>', RegexOptions\&.IgnoreCase)"
.br
.RI "Regex that matches the locations section in Movie Summary\&. "
.ti -1c
.RI "static readonly Regex \fBBudgetHeaderRegex\fP = new Regex(\fBBudget\fP + ':?', RegexOptions\&.IgnoreCase)"
.br
.RI "Regex that matches the budget section in Movie Summary\&. "
.ti -1c
.RI "static readonly Regex \fBProductionCompanyHeaderRegex\fP = new Regex(\fBProductionCompany\fP + ':?', RegexOptions\&.IgnoreCase)"
.br
.RI "Regex that matches the production company section in Movie Summary\&. "
.ti -1c
.RI "static readonly Regex \fBProductionCompanyLinkRegex\fP = new Regex(\fBCompaniesPath\fP + \fBCompanyIDPrefix\fP + @'(\\d+)\&.*?')"
.br
.RI "Regex that matches the production company link\&. "
.ti -1c
.RI "static readonly Regex \fBRuntimeHeaderRegex\fP = new Regex(\fBRuntime\fP + ':?', RegexOptions\&.IgnoreCase)"
.br
.RI "Regex that matches the runtime length section in Movie Summary\&. "
.ti -1c
.RI "static readonly Regex \fBCharacterEpisodeInfoRegex\fP = new Regex(@'\\n*\\s*\\(?(\\d+)\\s+eps\\s+•\\s+(\\d+)[\\\-–]?(\\d*)', RegexOptions\&.IgnoreCase)"
.br
.RI "Regex that matches the epsidoe info of a character\&. "
.ti -1c
.RI "static readonly Regex \fBBioHeightRegex\fP = new Regex(@'\\((\\d\\\&.\\d{1,2})\&.*m\\)')"
.br
.RI "Regex that matches the height of a person in Bio page\&. "
.ti -1c
.RI "static readonly Regex \fBIMDBIDRegex\fP = new Regex('(' + \fBMovieIDPrefix\fP + '|' + \fBPersonIDPrefix\fP + '|' + \fBCompanyIDPrefix\fP + @')(\\d+)')"
.br
.RI "Resource indipendent IMDb ID matcher regex\&. "
.ti -1c
.RI "static readonly Regex \fBCreditYearRegex\fP = new Regex(@'(\\d{4})(\\/\\w)?[–\-]?(\\d{4})?(\\/\\w)?')"
.br
.RI "Regex that matches the credit year\&. "
.ti -1c
.RI "static readonly Regex \fBRatingJSONLDMatcher\fP = new Regex(@'{''@type'':''AggregateRating''\&.+?}')"
.br
.RI "Regex that matches the rating out of context JSON\&. "
.ti -1c
.RI "static readonly Regex \fBRatingCountMatcher\fP = new Regex(@'''ratingCount''\\s*:\\s*(\\d+)')"
.br
.RI "Regex that matches the rating count out of rating JSON\&. "
.ti -1c
.RI "static readonly Regex \fBRatingValueMatcher\fP = new Regex(@'''ratingValue'':([\\d\\\&.,]*)')"
.br
.RI "Regex that matches the rating value out of rating JSON\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class that holds constant definitions that are related to IMDb\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
