.TH "JMovies.IMDb.Entities.Movies.ReleaseDate" 3 "Wed Mar 8 2023" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.Movies.ReleaseDate \- Class definition of release dates\&.  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "long \fBID\fP\fC [get, set]\fP"
.br
.RI "Primary Key\&. "
.ti -1c
.RI "DateTime \fBDate\fP\fC [get, set]\fP"
.br
.RI "Date of the release\&. "
.ti -1c
.RI "virtual \fBCountry\fP \fBCountry\fP\fC [get, set]\fP"
.br
.RI "Country of release date\&. "
.ti -1c
.RI "long \fBCountryID\fP\fC [get, set]\fP"
.br
.RI "Reference field for country\&. "
.ti -1c
.RI "string \fBDescription\fP\fC [get, set]\fP"
.br
.RI "Description related to the release date\&. "
.ti -1c
.RI "long \fBProductionID\fP\fC [get, set]\fP"
.br
.RI "Reference field for related Production\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class definition of release dates\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
