.TH "JMovies.IMDb.Factories.CreditFactory" 3 "Wed Sep 11 2019" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Factories.CreditFactory \- Factory class that is responsible for building credits based on the role type  

.SH SYNOPSIS
.br
.PP
.PP
Inherits IFactory< Credit, CreditRoleType >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCredit\fP \fBBuild\fP (\fBCreditRoleType\fP type)"
.br
.RI "Build method of Credit Factory that produces the given type of credits "
.in -1c
.SH "Detailed Description"
.PP 
Factory class that is responsible for building credits based on the role type 


.SH "Member Function Documentation"
.PP 
.SS "\fBCredit\fP JMovies\&.IMDb\&.Factories\&.CreditFactory\&.Build (\fBCreditRoleType\fP type)"

.PP
Build method of Credit Factory that produces the given type of credits 
.PP
\fBParameters\fP
.RS 4
\fItype\fP Type of credits to be produced
.RE
.PP
\fBReturns\fP
.RS 4
New credit instance
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
