.TH "JMovies.IMDb.Entities.Settings.ProductionDataFetchSettings" 3 "Tue Feb 8 2022" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.Settings.ProductionDataFetchSettings \- Class that is responsible for holding settings for Production data fetching  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBJMovies\&.IMDb\&.Entities\&.Settings\&.Presets\&.BasicProductionDataFetchSettings\fP, and \fBJMovies\&.IMDb\&.Entities\&.Settings\&.Presets\&.FullProductionDataFetchSettings\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual bool \fBFetchDetailedCast\fP\fC [get, set]\fP"
.br
.RI "Should the detailed cast info be fetched? This effects the response time\&. "
.ti -1c
.RI "virtual bool \fBFetchImageContents\fP\fC [get, set]\fP"
.br
.RI "Should the byte array content of the images be fetched along with URLs "
.ti -1c
.RI "virtual int \fBMediaImagesFetchCount\fP\fC [get, set]\fP"
.br
.RI "Number of media images to be fetched along with the production "
.ti -1c
.RI "virtual int \fBCastFetchCount\fP\fC [get, set]\fP"
.br
.RI "Number of cast to be fetched along with the production "
.in -1c
.SH "Detailed Description"
.PP 
Class that is responsible for holding settings for Production data fetching 


.SH "Property Documentation"
.PP 
.SS "virtual int JMovies\&.IMDb\&.Entities\&.Settings\&.ProductionDataFetchSettings\&.CastFetchCount\fC [get]\fP, \fC [set]\fP"

.PP
Number of cast to be fetched along with the production 
.SS "virtual bool JMovies\&.IMDb\&.Entities\&.Settings\&.ProductionDataFetchSettings\&.FetchDetailedCast\fC [get]\fP, \fC [set]\fP"

.PP
Should the detailed cast info be fetched? This effects the response time\&. 
.SS "virtual bool JMovies\&.IMDb\&.Entities\&.Settings\&.ProductionDataFetchSettings\&.FetchImageContents\fC [get]\fP, \fC [set]\fP"

.PP
Should the byte array content of the images be fetched along with URLs 
.SS "virtual int JMovies\&.IMDb\&.Entities\&.Settings\&.ProductionDataFetchSettings\&.MediaImagesFetchCount\fC [get]\fP, \fC [set]\fP"

.PP
Number of media images to be fetched along with the production 

.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
