.TH "JMovies.IMDb.Entities.Movies.ProductionLanguage" 3 "Sun Feb 26 2023" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.Movies.ProductionLanguage \- Class definition that handles language to production mapping\&.  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "long \fBID\fP\fC [get, set]\fP"
.br
.RI "Primary Key\&. "
.ti -1c
.RI "virtual \fBLanguage\fP \fBLanguage\fP\fC [get, set]\fP"
.br
.RI "Language of the production\&. "
.ti -1c
.RI "virtual \fBProduction\fP \fBProduction\fP\fC [get, set]\fP"
.br
.RI "Related Production\&. "
.ti -1c
.RI "long \fBProductionID\fP\fC [get, set]\fP"
.br
.RI "Reference id of the production\&. "
.ti -1c
.RI "long \fBLanguageID\fP\fC [get, set]\fP"
.br
.RI "Reference id of the language\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class definition that handles language to production mapping\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
