.TH "JMovies.IMDb.Tests.Production.TVShowTests" 3 "Wed Jul 20 2022" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Tests.Production.TVShowTests \- Test class that contains the tests dedicated for TV Show specific information  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBTVShowWithNoEndTest\fP ()"
.br
.RI "Test Method that tests a production with start date but no end date "
.ti -1c
.RI "void \fBSummaryTVShowTest\fP ()"
.br
.RI "Test Method that tests a TV Show with the summary fetch settings "
.in -1c
.SH "Detailed Description"
.PP 
Test class that contains the tests dedicated for TV Show specific information 


.SH "Member Function Documentation"
.PP 
.SS "void JMovies\&.IMDb\&.Tests\&.Production\&.TVShowTests\&.SummaryTVShowTest ()"

.PP
Test Method that tests a TV Show with the summary fetch settings 
.SS "void JMovies\&.IMDb\&.Tests\&.Production\&.TVShowTests\&.TVShowWithNoEndTest ()"

.PP
Test Method that tests a production with start date but no end date 

.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
