.TH "JMovies.IMDb.Entities.Movies.LDJson.Metadata" 3 "Thu Feb 16 2023" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.Movies.LDJson.Metadata \- Class representing the metadata linked to the page\&.  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBProductionType\fP\fC [get, set]\fP"
.br
.RI "Property representing the production's type\&. "
.ti -1c
.RI "string \fBDescription\fP\fC [get, set]\fP"
.br
.RI "Property representing the production's description\&. "
.ti -1c
.RI "string \fBURL\fP\fC [get, set]\fP"
.br
.RI "Property representing the production's URL\&. "
.ti -1c
.RI "\fBInfo\fP[] \fBActors\fP\fC [get, set]\fP"
.br
.RI "Property representing the actor list of the production\&. "
.ti -1c
.RI "\fBInfo\fP[] \fBCreators\fP\fC [get, set]\fP"
.br
.RI "Property representing the creator list of the production\&. "
.ti -1c
.RI "string \fBReleaseDate\fP\fC [get, set]\fP"
.br
.RI "Property representing the release date of the production\&. "
.ti -1c
.RI "string[] \fBGenres\fP\fC [get, set]\fP"
.br
.RI "Property representing the genre list of the production\&. "
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.RI "Property representing the name of the production\&. "
.ti -1c
.RI "string \fBKeywords\fP\fC [get, set]\fP"
.br
.RI "Property representing the keywords related to the production\&. "
.ti -1c
.RI "string \fBImage\fP\fC [get, set]\fP"
.br
.RI "Property representing the main image related to the production\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class representing the metadata linked to the page\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
