.TH "JMovies.IMDb.Entities.Settings.PersonDataFetchSettings" 3 "Sun Dec 8 2019" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.Settings.PersonDataFetchSettings \- Class that is responsible for holding settings for Person data fetching  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBJMovies\&.IMDb\&.Entities\&.Settings\&.Presets\&.BasicPersonDataFetchSettings\fP, and \fBJMovies\&.IMDb\&.Entities\&.Settings\&.Presets\&.FullPersonDataFetchSettings\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual bool \fBFetchBioPage\fP\fC [get, set]\fP"
.br
.RI "Should the Bio Page details be also fetched? This effects the response time "
.ti -1c
.RI "virtual bool \fBFetchImageContents\fP\fC [get, set]\fP"
.br
.RI "Should the byte array content of the images be fetched along with URLs "
.ti -1c
.RI "virtual int \fBMediaImagesFetchCount\fP\fC [get, set]\fP"
.br
.RI "Number of media images to be fetched along with the person "
.in -1c
.SH "Detailed Description"
.PP 
Class that is responsible for holding settings for Person data fetching 


.SH "Property Documentation"
.PP 
.SS "virtual bool JMovies\&.IMDb\&.Entities\&.Settings\&.PersonDataFetchSettings\&.FetchBioPage\fC [get]\fP, \fC [set]\fP"

.PP
Should the Bio Page details be also fetched? This effects the response time 
.SS "virtual bool JMovies\&.IMDb\&.Entities\&.Settings\&.PersonDataFetchSettings\&.FetchImageContents\fC [get]\fP, \fC [set]\fP"

.PP
Should the byte array content of the images be fetched along with URLs 
.SS "virtual int JMovies\&.IMDb\&.Entities\&.Settings\&.PersonDataFetchSettings\&.MediaImagesFetchCount\fC [get]\fP, \fC [set]\fP"

.PP
Number of media images to be fetched along with the person 

.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
