.TH "JMovies.IMDb.Helpers.Movies" 3 "Mon Sep 9 2019" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Helpers.Movies
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMoviePageDetailsHelper\fP"
.br
.RI "Class responsible for parsing the Movie Page Details "
.ti -1c
.RI "class \fBPhotoGalleryPageHelper\fP"
.br
.RI "Class responsible for parsing the Media Images "
.ti -1c
.RI "class \fBReleaseInfoPageHelper\fP"
.br
.RI "Helper Class responsible for parsing the Release Info Page "
.ti -1c
.RI "class \fBSummaryCastHelper\fP"
.br
.RI "Class responsible for parsing Cast Summary Section "
.ti -1c
.RI "class \fBSummaryStorylineHelper\fP"
.br
.RI "Class responsible for parsing the summary-story line section "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
