.TH "JMovies.IMDb.Helpers.Movies.ReleaseInfoPageHelper" 3 "Sun Sep 8 2019" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Helpers.Movies.ReleaseInfoPageHelper \- Helper Class responsible for parsing the Release Info Page  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBParse\fP (\fBMovie\fP movie, HtmlDocument releaseInfoPageDocument)"
.br
.RI "Parses the Release Info Page and persists the data on Movie instance "
.in -1c
.SH "Detailed Description"
.PP 
Helper Class responsible for parsing the Release Info Page 


.SH "Member Function Documentation"
.PP 
.SS "static void JMovies\&.IMDb\&.Helpers\&.Movies\&.ReleaseInfoPageHelper\&.Parse (\fBMovie\fP movie, HtmlDocument releaseInfoPageDocument)\fC [static]\fP"

.PP
Parses the Release Info Page and persists the data on Movie instance 
.PP
\fBParameters\fP
.RS 4
\fImovie\fP Movie object to be populated
.br
\fIreleaseInfoPageDocument\fP HTML Document of the Release Info Page
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
