.TH "JMovies.IMDb.Entities.Movies.Movie" 3 "Wed Jul 20 2022" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.Movies.Movie \- Class definition of a movie  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBJMovies\&.IMDb\&.Entities\&.Movies\&.Production\fP\&.
.PP
Inherited by \fBJMovies\&.IMDb\&.Entities\&.Movies\&.TVSeries\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "override \fBProductionTypeEnum\fP \fBProductionType\fP => \fBProductionTypeEnum\&.Movie\fP"
.br
.RI "Type of the production "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBOriginalTitle\fP\fC [get, set]\fP"
.br
.RI "Original Title of the movie "
.ti -1c
.RI "string \fBPlotSummary\fP\fC [get, set]\fP"
.br
.RI "Plot Summary of the movie "
.ti -1c
.RI "string \fBStoryLine\fP\fC [get, set]\fP"
.br
.RI "Story Line of the movie "
.ti -1c
.RI "virtual ICollection< \fBCredit\fP > \fBCredits\fP\fC [get, set]\fP"
.br
.RI "Credits of the movie "
.ti -1c
.RI "virtual ICollection< \fBTagLine\fP > \fBTagLines\fP\fC [get, set]\fP"
.br
.RI "Tag Lines of the movie "
.ti -1c
.RI "virtual ICollection< \fBKeyword\fP > \fBKeywords\fP\fC [get, set]\fP"
.br
.RI "Keywords of the movie "
.ti -1c
.RI "virtual ICollection< \fBGenre\fP > \fBGenres\fP\fC [get, set]\fP"
.br
.RI "Genres of the movie "
.ti -1c
.RI "ICollection< \fBOfficialSite\fP > \fBOfficialSites\fP\fC [get, set]\fP"
.br
.RI "Official Sites of the movie "
.ti -1c
.RI "virtual ICollection< \fBProductionCountry\fP > \fBCountries\fP\fC [get, set]\fP"
.br
.RI "Countries of the movie "
.ti -1c
.RI "virtual ICollection< \fBProductionLanguage\fP > \fBLanguages\fP\fC [get, set]\fP"
.br
.RI "Languages of the movie "
.ti -1c
.RI "virtual ICollection< \fBReleaseDate\fP > \fBReleaseDates\fP\fC [get, set]\fP"
.br
.RI "Release dates of the movie "
.ti -1c
.RI "virtual ICollection< \fBAKA\fP > \fBAKAs\fP\fC [get, set]\fP"
.br
.RI "Alternative names of the movie "
.ti -1c
.RI "virtual ICollection< string > \fBFilmingLocations\fP\fC [get, set]\fP"
.br
.RI "Filming Locations of the movie "
.ti -1c
.RI "\fBBudget\fP \fBBudget\fP\fC [get, set]\fP"
.br
.RI "\fBBudget\fP of the movie "
.ti -1c
.RI "virtual ICollection< \fBCompany\fP > \fBProductionCompanies\fP\fC [get, set]\fP"
.br
.RI "\fBProduction\fP Companies of the movie "
.ti -1c
.RI "TimeSpan \fBRuntime\fP\fC [get, set]\fP"
.br
.RI "Length of the movie "
.in -1c
.SH "Detailed Description"
.PP 
Class definition of a movie 


.SH "Member Data Documentation"
.PP 
.SS "override \fBProductionTypeEnum\fP JMovies\&.IMDb\&.Entities\&.Movies\&.Movie\&.ProductionType => \fBProductionTypeEnum\&.Movie\fP"

.PP
Type of the production 
.SH "Property Documentation"
.PP 
.SS "virtual ICollection<\fBAKA\fP> JMovies\&.IMDb\&.Entities\&.Movies\&.Movie\&.AKAs\fC [get]\fP, \fC [set]\fP"

.PP
Alternative names of the movie 
.SS "\fBBudget\fP JMovies\&.IMDb\&.Entities\&.Movies\&.Movie\&.Budget\fC [get]\fP, \fC [set]\fP"

.PP
\fBBudget\fP of the movie 
.SS "virtual ICollection<\fBProductionCountry\fP> JMovies\&.IMDb\&.Entities\&.Movies\&.Movie\&.Countries\fC [get]\fP, \fC [set]\fP"

.PP
Countries of the movie 
.SS "virtual ICollection<\fBCredit\fP> JMovies\&.IMDb\&.Entities\&.Movies\&.Movie\&.Credits\fC [get]\fP, \fC [set]\fP"

.PP
Credits of the movie 
.SS "virtual ICollection<string> JMovies\&.IMDb\&.Entities\&.Movies\&.Movie\&.FilmingLocations\fC [get]\fP, \fC [set]\fP"

.PP
Filming Locations of the movie 
.SS "virtual ICollection<\fBGenre\fP> JMovies\&.IMDb\&.Entities\&.Movies\&.Movie\&.Genres\fC [get]\fP, \fC [set]\fP"

.PP
Genres of the movie 
.SS "virtual ICollection<\fBKeyword\fP> JMovies\&.IMDb\&.Entities\&.Movies\&.Movie\&.Keywords\fC [get]\fP, \fC [set]\fP"

.PP
Keywords of the movie 
.SS "virtual ICollection<\fBProductionLanguage\fP> JMovies\&.IMDb\&.Entities\&.Movies\&.Movie\&.Languages\fC [get]\fP, \fC [set]\fP"

.PP
Languages of the movie 
.SS "ICollection<\fBOfficialSite\fP> JMovies\&.IMDb\&.Entities\&.Movies\&.Movie\&.OfficialSites\fC [get]\fP, \fC [set]\fP"

.PP
Official Sites of the movie 
.SS "string JMovies\&.IMDb\&.Entities\&.Movies\&.Movie\&.OriginalTitle\fC [get]\fP, \fC [set]\fP"

.PP
Original Title of the movie 
.SS "string JMovies\&.IMDb\&.Entities\&.Movies\&.Movie\&.PlotSummary\fC [get]\fP, \fC [set]\fP"

.PP
Plot Summary of the movie 
.SS "virtual ICollection<\fBCompany\fP> JMovies\&.IMDb\&.Entities\&.Movies\&.Movie\&.ProductionCompanies\fC [get]\fP, \fC [set]\fP"

.PP
\fBProduction\fP Companies of the movie 
.SS "virtual ICollection<\fBReleaseDate\fP> JMovies\&.IMDb\&.Entities\&.Movies\&.Movie\&.ReleaseDates\fC [get]\fP, \fC [set]\fP"

.PP
Release dates of the movie 
.SS "TimeSpan JMovies\&.IMDb\&.Entities\&.Movies\&.Movie\&.Runtime\fC [get]\fP, \fC [set]\fP"

.PP
Length of the movie 
.SS "string JMovies\&.IMDb\&.Entities\&.Movies\&.Movie\&.StoryLine\fC [get]\fP, \fC [set]\fP"

.PP
Story Line of the movie 
.SS "virtual ICollection<\fBTagLine\fP> JMovies\&.IMDb\&.Entities\&.Movies\&.Movie\&.TagLines\fC [get]\fP, \fC [set]\fP"

.PP
Tag Lines of the movie 

.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
