.TH "JMovies.IMDb.Helpers.People.BioPageHelper" 3 "Sat Dec 7 2019" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Helpers.People.BioPageHelper \- Class responsible for parsing the Bio Page  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBParseBioPage\fP (\fBPerson\fP person)"
.br
.RI "Method responsible for parsing the Bio Page "
.in -1c
.SH "Detailed Description"
.PP 
Class responsible for parsing the Bio Page 


.SH "Member Function Documentation"
.PP 
.SS "static void JMovies\&.IMDb\&.Helpers\&.People\&.BioPageHelper\&.ParseBioPage (\fBPerson\fP person)\fC [static]\fP"

.PP
Method responsible for parsing the Bio Page 
.PP
\fBParameters\fP
.RS 4
\fIperson\fP Person to be populated
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
