.TH "JMovies.IMDb.Tests.Person.PersonGalleryTests" 3 "Wed Jul 20 2022" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Tests.Person.PersonGalleryTests \- Test suite for tests related to fetching of the gallery page of the persons  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBFetchingLimitedImages\fP ()"
.br
.RI "Fetches the person data with 5 images "
.ti -1c
.RI "void \fBFetchingWithPagination\fP ()"
.br
.RI "Fetches the person data with 55 images "
.in -1c
.SH "Detailed Description"
.PP 
Test suite for tests related to fetching of the gallery page of the persons 


.SH "Member Function Documentation"
.PP 
.SS "void JMovies\&.IMDb\&.Tests\&.Person\&.PersonGalleryTests\&.FetchingLimitedImages ()"

.PP
Fetches the person data with 5 images 
.SS "void JMovies\&.IMDb\&.Tests\&.Person\&.PersonGalleryTests\&.FetchingWithPagination ()"

.PP
Fetches the person data with 55 images 

.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
