.TH "JMovies.IMDb.Entities.Movies.ReleaseDate" 3 "Sat Sep 14 2019" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.Movies.ReleaseDate \- Class definition of release dates  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "long \fBID\fP\fC [get, set]\fP"
.br
.RI "Primary Key "
.ti -1c
.RI "DateTime \fBDate\fP\fC [get, set]\fP"
.br
.RI "Date of the release "
.ti -1c
.RI "virtual \fBCountry\fP \fBCountry\fP\fC [get, set]\fP"
.br
.RI "\fBCountry\fP of release date "
.ti -1c
.RI "long \fBCountryID\fP\fC [get, set]\fP"
.br
.RI "Reference field for country "
.ti -1c
.RI "string \fBDescription\fP\fC [get, set]\fP"
.br
.RI "Description related to the release date "
.ti -1c
.RI "long \fBProductionID\fP\fC [get, set]\fP"
.br
.RI "Reference field for related \fBProduction\fP "
.in -1c
.SH "Detailed Description"
.PP 
Class definition of release dates 


.SH "Property Documentation"
.PP 
.SS "virtual \fBCountry\fP JMovies\&.IMDb\&.Entities\&.Movies\&.ReleaseDate\&.Country\fC [get]\fP, \fC [set]\fP"

.PP
\fBCountry\fP of release date 
.SS "long JMovies\&.IMDb\&.Entities\&.Movies\&.ReleaseDate\&.CountryID\fC [get]\fP, \fC [set]\fP"

.PP
Reference field for country 
.SS "DateTime JMovies\&.IMDb\&.Entities\&.Movies\&.ReleaseDate\&.Date\fC [get]\fP, \fC [set]\fP"

.PP
Date of the release 
.SS "string JMovies\&.IMDb\&.Entities\&.Movies\&.ReleaseDate\&.Description\fC [get]\fP, \fC [set]\fP"

.PP
Description related to the release date 
.SS "long JMovies\&.IMDb\&.Entities\&.Movies\&.ReleaseDate\&.ID\fC [get]\fP, \fC [set]\fP"

.PP
Primary Key 
.SS "long JMovies\&.IMDb\&.Entities\&.Movies\&.ReleaseDate\&.ProductionID\fC [get]\fP, \fC [set]\fP"

.PP
Reference field for related \fBProduction\fP 

.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
