.TH "JMovies.IMDb.Entities.Settings" 3 "Sun Sep 8 2019" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.Settings
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPersonDataFetchSettings\fP"
.br
.RI "Class that is responsible for holding settings for Person data fetching "
.ti -1c
.RI "class \fBProductionDataFetchSettings\fP"
.br
.RI "Class that is responsible for holding settings for Production data fetching "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
