.TH "JMovies.IMDb.Entities.Movies.Company" 3 "Mon Dec 9 2019" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.Movies.Company \- Class definition of a company related to the industry  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "long \fBID\fP\fC [get, set]\fP"
.br
.RI "ID of the company "
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.RI "Name of the company "
.ti -1c
.RI "long \fBProductionID\fP\fC [get, set]\fP"
.br
.RI "Reference field for \fBProduction\fP "
.in -1c
.SH "Detailed Description"
.PP 
Class definition of a company related to the industry 


.SH "Property Documentation"
.PP 
.SS "long JMovies\&.IMDb\&.Entities\&.Movies\&.Company\&.ID\fC [get]\fP, \fC [set]\fP"

.PP
ID of the company 
.SS "string JMovies\&.IMDb\&.Entities\&.Movies\&.Company\&.Name\fC [get]\fP, \fC [set]\fP"

.PP
Name of the company 
.SS "long JMovies\&.IMDb\&.Entities\&.Movies\&.Company\&.ProductionID\fC [get]\fP, \fC [set]\fP"

.PP
Reference field for \fBProduction\fP 

.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
