.TH "JMovies.IMDb.Factories.ProductionFactory" 3 "Sun Feb 26 2023" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Factories.ProductionFactory \- Factory class that is responsible for building productions based on the type\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits IFactory< Production, ProductionTypeEnum >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProduction\fP \fBBuild\fP (\fBProductionTypeEnum\fP type)"
.br
.RI "Build method of Production Factory that produces the given type of productions\&. "
.in -1c
.SH "Detailed Description"
.PP 
Factory class that is responsible for building productions based on the type\&. 
.SH "Member Function Documentation"
.PP 
.SS "\fBProduction\fP JMovies\&.IMDb\&.Factories\&.ProductionFactory\&.Build (\fBProductionTypeEnum\fP type)"

.PP
Build method of Production Factory that produces the given type of productions\&. 
.PP
\fBParameters\fP
.RS 4
\fItype\fP Type of production to be produced
.RE
.PP
\fBReturns\fP
.RS 4
New production instance
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
