.TH "JMovies.IMDb.Factories" 3 "Sun Sep 15 2019" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Factories
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCreditFactory\fP"
.br
.RI "Factory class that is responsible for building credits based on the role type "
.ti -1c
.RI "class \fBProductionFactory\fP"
.br
.RI "Factory class that is responsible for building productions based on the type "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
