.TH "JMovies.IMDb.Entities.PrivateAPI" 3 "Wed Mar 8 2023" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.PrivateAPI
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAPIData\fP"
.br
.RI "Class Definition of a private API Response\&. "
.ti -1c
.RI "class \fBAPIResponse\fP"
.br
.RI "Class Definition of a private API Response\&. "
.ti -1c
.RI "class \fBDisplayableProperty\fP"
.br
.RI "Class Definition of a private Displayable Property\&. "
.ti -1c
.RI "class \fBDisplayablePropertyValue\fP"
.br
.RI "Class Definition of a private Displayable Property Value\&. "
.ti -1c
.RI "class \fBProductionData\fP"
.br
.RI "Class Definition of a private Production Data\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
