.TH "JMovies.IMDb.Entities.Movies.Budget" 3 "Thu Feb 16 2023" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.Movies.Budget \- Class definition of Budget of a Title\&.  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBDescription\fP\fC [get, set]\fP"
.br
.RI "Description related to the budget information\&. "
.ti -1c
.RI "\fBAmount\fP \fBAmount\fP\fC [get, set]\fP"
.br
.RI "Amount of the budget of the title\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class definition of Budget of a Title\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
