.TH "JMovies.IMDb.Entities.Settings.ProductionDataFetchSettings" 3 "Wed Mar 8 2023" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.Settings.ProductionDataFetchSettings \- Class that is responsible for holding settings for Production data fetching\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBJMovies\&.IMDb\&.Entities\&.Settings\&.BaseDataFetchSettings\fP\&.
.PP
Inherited by \fBJMovies\&.IMDb\&.Entities\&.Settings\&.Presets\&.BasicProductionDataFetchSettings\fP, and \fBJMovies\&.IMDb\&.Entities\&.Settings\&.Presets\&.FullProductionDataFetchSettings\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual bool \fBFetchDetailedCast\fP\fC [get, set]\fP"
.br
.RI "Should the detailed cast info be fetched? This effects the response time\&. "
.ti -1c
.RI "virtual bool \fBFetchImageContents\fP\fC [get, set]\fP"
.br
.RI "Should the byte array content of the images be fetched along with URLs\&. "
.ti -1c
.RI "virtual int \fBMediaImagesFetchCount\fP\fC [get, set]\fP"
.br
.RI "Number of media images to be fetched along with the production\&. "
.ti -1c
.RI "virtual int \fBCastFetchCount\fP\fC [get, set]\fP"
.br
.RI "Number of cast to be fetched along with the production\&. "
.in -1c

Properties inherited from \fBJMovies\&.IMDb\&.Entities\&.Settings\&.BaseDataFetchSettings\fP
.in +1c
.ti -1c
.RI "virtual string \fBPreferredCulture\fP\fC [get, set]\fP"
.br
.RI "Preferred culture for fetching data (where applicable) "
.ti -1c
.RI "virtual bool \fBFetchPrivateData\fP\fC [get, set]\fP"
.br
.RI "Toggles fetching private data available through normally user-click on the website\&. DISCLAIMER: Use this only on private projects\&. Usage of these APIs are not allowed for non-private purposes\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class that is responsible for holding settings for Production data fetching\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
