.TH "JMovies.IMDb.Entities.Movies.Character" 3 "Thu Feb 16 2023" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.Movies.Character \- Class definition of a character in a title\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBJMovies\&.IMDb\&.Entities\&.Movies\&.TVCharacter\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "long \fBID\fP\fC [get, set]\fP"
.br
.RI "Primary key of a character\&. "
.ti -1c
.RI "virtual \fBCharacterTypeEnum\fP \fBCharacterType\fP\fC [get, set]\fP"
.br
.RI "Underlining Character Type\&. "
.ti -1c
.RI "long? \fBIMDbID\fP\fC [get, set]\fP"
.br
.RI "IMDb ID\&. "
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.RI "Name of the character\&. "
.ti -1c
.RI "long \fBCreditID\fP\fC [get, set]\fP"
.br
.RI "Reference ID of related credit\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class definition of a character in a title\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
