.TH "JMovies.IMDb.Common.Constants.GeneralRegexConstants" 3 "Wed Mar 8 2023" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Common.Constants.GeneralRegexConstants \- Class responsible for holding the Regex definitions that are commonly used\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly Regex \fBAmountStringRegex\fP = new Regex(@'^([^a\-zA\-Z0\-9_\\s\\n]*\\s?|[a\-zA\-Z]{2,3}\\s?)([\\d\\\&.,]+)(\\s?[^a\-zA\-Z0\-9_\\s\\n]*|\\s?[a\-zA\-Z]{2,3})\\((\&.+)\\)')"
.br
.RI "Regex that captures any money string\&. "
.ti -1c
.RI "static readonly Regex \fBHtmlDatetimeTagRegex\fP = new Regex(@'PT(\\d*D)?(\\d*H)?(\\d*M)?(\\d*S)?')"
.br
.RI "Regex that captures and groups the HTML Datetime attribute details\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class responsible for holding the Regex definitions that are commonly used\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
