.TH "JMovies.IMDb.Entities.People" 3 "Wed Mar 8 2023" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.People
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBActor\fP"
.br
.RI "Class definition of an actor\&. "
.ti -1c
.RI "class \fBPerson\fP"
.br
.RI "Class definition of a person\&. "
.ti -1c
.RI "class \fBProductionCredit\fP"
.br
.RI "Credit of a person in a specific production\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBGenderEnum\fP { \fBUndefined\fP, \fBMale\fP, \fBFemale\fP }"
.br
.RI "Enumeration of genders\&. "
.ti -1c
.RI "enum \fBPersonTypeEnum\fP { \fBUndefined\fP, \fBActor\fP }"
.br
.RI "Class definition of person types\&. "
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum JMovies\&.IMDb\&.Entities\&.People\&.GenderEnum"

.PP
Enumeration of genders\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIUndefined \fP\fP
Default Gender\&. 
.TP
\fB\fIMale \fP\fP
Male\&. 
.TP
\fB\fIFemale \fP\fP
Female\&. 
.SS "enum JMovies\&.IMDb\&.Entities\&.People\&.PersonTypeEnum"

.PP
Class definition of person types\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIUndefined \fP\fP
Default Person Type\&. 
.TP
\fB\fIActor \fP\fP
Actor type of Person\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
