.TH "JMovies.IMDb.Tests.Production.ProductionAsyncTests" 3 "Tue Feb 14 2023" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Tests.Production.ProductionAsyncTests \- Test class that contains the tests for basic async scraping scenarios for productions\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "async Task \fBBasicFetchingTest\fP ()"
.br
.RI "Test that checks if the code is running correctly in async mode\&. "
.ti -1c
.RI "void \fBNonBlockingTest\fP ()"
.br
.RI "Test that checks if the code is running without blocking\&. "
.in -1c
.SH "Detailed Description"
.PP 
Test class that contains the tests for basic async scraping scenarios for productions\&. 
.SH "Member Function Documentation"
.PP 
.SS "async Task JMovies\&.IMDb\&.Tests\&.Production\&.ProductionAsyncTests\&.BasicFetchingTest ()"

.PP
Test that checks if the code is running correctly in async mode\&. 
.PP
\fBReturns\fP
.RS 4

.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
