.TH "JMovies.IMDb.Entities.Movies.OfficialSite" 3 "Sun Feb 26 2023" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.Movies.OfficialSite \- Class definition of an Official Site\&.  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBTitle\fP\fC [get, set]\fP"
.br
.RI "Title of the official website\&. "
.ti -1c
.RI "string \fBURL\fP\fC [get, set]\fP"
.br
.RI "URL of the official website\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class definition of an Official Site\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
