.TH "JMovies.IMDb.Entities.Movies.Rating" 3 "Wed Sep 11 2019" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.Movies.Rating \- Class definition of Ratings  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRating\fP (\fBDataSourceTypeEnum\fP dataSourceType, \fBProduction\fP production)"
.br
.RI "Constructor by type of the datasource "
.ti -1c
.RI "\fBRating\fP ()"
.br
.RI "Default constructor "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "long \fBID\fP\fC [get, set]\fP"
.br
.RI "Primary key "
.ti -1c
.RI "double \fBValue\fP\fC [get, set]\fP"
.br
.RI "Value of the rating "
.ti -1c
.RI "long \fBRateCount\fP\fC [get, set]\fP"
.br
.RI "Count of rates "
.ti -1c
.RI "virtual \fBDataSource\fP \fBDataSource\fP\fC [get, set]\fP"
.br
.RI "Source of the rating data "
.ti -1c
.RI "int \fBDataSourceID\fP\fC [get, set]\fP"
.br
.RI "Reference field for DataSource "
.ti -1c
.RI "virtual \fBProduction\fP \fBProduction\fP\fC [get, set]\fP"
.br
.RI "Related production "
.ti -1c
.RI "long \fBProductionID\fP\fC [get, set]\fP"
.br
.RI "Reference field for \fBProduction\fP "
.in -1c
.SH "Detailed Description"
.PP 
Class definition of Ratings 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "JMovies\&.IMDb\&.Entities\&.Movies\&.Rating\&.Rating (\fBDataSourceTypeEnum\fP dataSourceType, \fBProduction\fP production)"

.PP
Constructor by type of the datasource 
.PP
\fBParameters\fP
.RS 4
\fIdataSourceType\fP Type of the data source
.br
\fIproduction\fP Related \fBProduction\fP instance
.RE
.PP

.SS "JMovies\&.IMDb\&.Entities\&.Movies\&.Rating\&.Rating ()"

.PP
Default constructor 
.SH "Property Documentation"
.PP 
.SS "virtual \fBDataSource\fP JMovies\&.IMDb\&.Entities\&.Movies\&.Rating\&.DataSource\fC [get]\fP, \fC [set]\fP"

.PP
Source of the rating data 
.SS "int JMovies\&.IMDb\&.Entities\&.Movies\&.Rating\&.DataSourceID\fC [get]\fP, \fC [set]\fP"

.PP
Reference field for DataSource 
.SS "long JMovies\&.IMDb\&.Entities\&.Movies\&.Rating\&.ID\fC [get]\fP, \fC [set]\fP"

.PP
Primary key 
.SS "virtual \fBProduction\fP JMovies\&.IMDb\&.Entities\&.Movies\&.Rating\&.Production\fC [get]\fP, \fC [set]\fP"

.PP
Related production 
.SS "long JMovies\&.IMDb\&.Entities\&.Movies\&.Rating\&.ProductionID\fC [get]\fP, \fC [set]\fP"

.PP
Reference field for \fBProduction\fP 
.SS "long JMovies\&.IMDb\&.Entities\&.Movies\&.Rating\&.RateCount\fC [get]\fP, \fC [set]\fP"

.PP
Count of rates 
.SS "double JMovies\&.IMDb\&.Entities\&.Movies\&.Rating\&.Value\fC [get]\fP, \fC [set]\fP"

.PP
Value of the rating 

.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
