.TH "JMovies.IMDb.Entities.Movies" 3 "Sat Sep 14 2019" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.Movies
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBActingCredit\fP"
.br
.RI "Class definition of an Acting \fBCredit\fP "
.ti -1c
.RI "class \fBAKA\fP"
.br
.RI "Class definition for other names of the title "
.ti -1c
.RI "class \fBBudget\fP"
.br
.RI "Class definition of \fBBudget\fP of a Title "
.ti -1c
.RI "class \fBCharacter\fP"
.br
.RI "Class definition of a character in a title "
.ti -1c
.RI "class \fBCompany\fP"
.br
.RI "Class definition of a company related to the industry "
.ti -1c
.RI "class \fBCountry\fP"
.br
.RI "Class definition of a country "
.ti -1c
.RI "class \fBCredit\fP"
.br
.RI "Class definition of a credit in a title "
.ti -1c
.RI "class \fBGenre\fP"
.br
.RI "Class definition of a genre "
.ti -1c
.RI "class \fBKeyword\fP"
.br
.RI "Class definition of a keyword related to a title "
.ti -1c
.RI "class \fBLanguage\fP"
.br
.RI "Class definition of a language "
.ti -1c
.RI "class \fBMovie\fP"
.br
.RI "Class definition of a movie "
.ti -1c
.RI "class \fBOfficialSite\fP"
.br
.RI "Class definition of an Official Site "
.ti -1c
.RI "class \fBProduction\fP"
.br
.RI "Base class of any production "
.ti -1c
.RI "class \fBProductionCountry\fP"
.br
.RI "Class definition that handles country to production mapping "
.ti -1c
.RI "class \fBProductionLanguage\fP"
.br
.RI "Class definition that handles language to production mapping "
.ti -1c
.RI "class \fBRating\fP"
.br
.RI "Class definition of Ratings "
.ti -1c
.RI "class \fBReleaseDate\fP"
.br
.RI "Class definition of release dates "
.ti -1c
.RI "class \fBTagLine\fP"
.br
.RI "Tag line of the production "
.ti -1c
.RI "class \fBTVCharacter\fP"
.br
.RI "Class definition of a TV \fBCharacter\fP "
.ti -1c
.RI "class \fBTVSeries\fP"
.br
.RI "Class definition of TV Series "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBCharacterTypeEnum\fP { \fBCharacterTypeEnum\&.Character\fP, \fBCharacterTypeEnum\&.TVCharacter\fP }"
.br
.RI "Class definition of a character type "
.ti -1c
.RI "enum \fBCreditRoleType\fP { \fBCreditRoleType\&.Undefined\fP, \fBCreditRoleType\&.Director\fP, \fBCreditRoleType\&.Acting\fP, \fBCreditRoleType\&.Writer\fP, \fBCreditRoleType\&.Creator\fP, \fBCreditRoleType\&.Producer\fP, \fBCreditRoleType\&.Composer\fP, \fBCreditRoleType\&.MusicDepartment\fP, \fBCreditRoleType\&.Actor\fP, \fBCreditRoleType\&.Actress\fP }"
.br
.RI "Enumeration of Role Types in a credit "
.ti -1c
.RI "enum \fBProductionTypeEnum\fP { \fBProductionTypeEnum\&.Undefined\fP, \fBProductionTypeEnum\&.Movie\fP, \fBProductionTypeEnum\&.TVSeries\fP }"
.br
.RI "Enumeration of Production Types "
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBJMovies\&.IMDb\&.Entities\&.Movies\&.CharacterTypeEnum\fP\fC [strong]\fP"

.PP
Class definition of a character type 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fICharacter \fP\fP
A generic character 
.TP
\fB\fITVCharacter \fP\fP
A TV \fBCharacter\fP 
.SS "enum \fBJMovies\&.IMDb\&.Entities\&.Movies\&.CreditRoleType\fP\fC [strong]\fP"

.PP
Enumeration of Role Types in a credit 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIUndefined \fP\fP
Default Value of \fBCredit\fP Role 
.TP
\fB\fIDirector \fP\fP
Director role in a title 
.TP
\fB\fIActing \fP\fP
Acting role in a title 
.TP
\fB\fIWriter \fP\fP
Writer role in a title 
.TP
\fB\fICreator \fP\fP
Creator role in a title 
.TP
\fB\fIProducer \fP\fP
Producer role in a title 
.TP
\fB\fIComposer \fP\fP
Composer role in a title 
.TP
\fB\fIMusicDepartment \fP\fP
Part of a Music Department 
.TP
\fB\fIActor \fP\fP
Actor role in a title 
.TP
\fB\fIActress \fP\fP
Actress role in a title 
.SS "enum \fBJMovies\&.IMDb\&.Entities\&.Movies\&.ProductionTypeEnum\fP\fC [strong]\fP"

.PP
Enumeration of \fBProduction\fP Types 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIUndefined \fP\fP
Default \fBProduction\fP Type 
.TP
\fB\fIMovie \fP\fP
\fBMovie\fP 
.TP
\fB\fITVSeries \fP\fP
TV Series 
.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
