.TH "JMovies.IMDb.Tests.Person.BasicPersonScrapingTests" 3 "Thu Jul 28 2022" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Tests.Person.BasicPersonScrapingTests \- Test class that contains the tests for basic async scraping scenarios for persons  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBPersonScraping\fP ()"
.br
.RI "Method that tests scraping of person pages "
.ti -1c
.RI "void \fBDetailedPersonScraping\fP ()"
.br
.RI "Method that tests detailed scraping of person pages "
.in -1c
.SH "Detailed Description"
.PP 
Test class that contains the tests for basic async scraping scenarios for persons 


.SH "Member Function Documentation"
.PP 
.SS "void JMovies\&.IMDb\&.Tests\&.Person\&.BasicPersonScrapingTests\&.DetailedPersonScraping ()"

.PP
Method that tests detailed scraping of person pages 
.SS "void JMovies\&.IMDb\&.Tests\&.Person\&.BasicPersonScrapingTests\&.PersonScraping ()"

.PP
Method that tests scraping of person pages 

.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
