.TH "JMovies.IMDb.Entities.Movies.LDJson" 3 "Wed Mar 8 2023" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.Movies.LDJson
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBInfo\fP"
.br
.RI "Class representing a basic info linked to the production\&. "
.ti -1c
.RI "class \fBMetadata\fP"
.br
.RI "Class representing the metadata linked to the page\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
