.TH "JMovies.IMDb.Tests.Production" 3 "Tue Feb 14 2023" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Tests.Production
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAKATests\fP"
.br
.RI "Test class that contains the tests which are targeted for scraping culture related tests\&. "
.ti -1c
.RI "class \fBBasicProductionScrapingTests\fP"
.br
.RI "Test class that contains the tests for basic scraping scenarios for productions\&. "
.ti -1c
.RI "class \fBProductionAsyncTests\fP"
.br
.RI "Test class that contains the tests for basic async scraping scenarios for productions\&. "
.ti -1c
.RI "class \fBProductionGalleryTests\fP"
.br
.RI "Test suite for tests related to fetching of the gallery page of the productions\&. "
.ti -1c
.RI "class \fBScrapingCultureTests\fP"
.br
.RI "Test class that contains the tests which are targeted for scraping culture related tests\&. "
.ti -1c
.RI "class \fBSpecificMoviesTests\fP"
.br
.RI "Test class that contains the tests which are targeted for specific movies\&. "
.ti -1c
.RI "class \fBTVShowTests\fP"
.br
.RI "Test class that contains the tests dedicated for TV Show specific information\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
