.TH "JMovies.IMDb.Entities.Settings.Presets.BasicPersonDataFetchSettings" 3 "Mon Dec 9 2019" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.Settings.Presets.BasicPersonDataFetchSettings \- A preset of settings to fetch only basic person data  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBJMovies\&.IMDb\&.Entities\&.Settings\&.PersonDataFetchSettings\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBFetchBioPage\fP\fC [get]\fP"
.br
.RI "Do not fetch the bio page "
.ti -1c
.RI "override bool \fBFetchImageContents\fP\fC [get]\fP"
.br
.RI "Do not fetch image contents "
.in -1c
.SH "Detailed Description"
.PP 
A preset of settings to fetch only basic person data 


.SH "Property Documentation"
.PP 
.SS "override bool JMovies\&.IMDb\&.Entities\&.Settings\&.Presets\&.BasicPersonDataFetchSettings\&.FetchBioPage\fC [get]\fP"

.PP
Do not fetch the bio page 
.SS "override bool JMovies\&.IMDb\&.Entities\&.Settings\&.Presets\&.BasicPersonDataFetchSettings\&.FetchImageContents\fC [get]\fP"

.PP
Do not fetch image contents 

.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
