.TH "JMovies.IMDb.Entities.PrivateAPI.Production" 3 "Sun Feb 26 2023" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.PrivateAPI.Production
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAKAData\fP"
.br
.RI "Class Definition of a private Production AKA Data\&. "
.ti -1c
.RI "class \fBAKANode\fP"
.br
.RI "Class Definition of a private Production AKA Node\&. "
.ti -1c
.RI "class \fBAKAsEdge\fP"
.br
.RI "Class Definition of a private Production AKAs Edge\&. "
.ti -1c
.RI "class \fBCountryInfo\fP"
.br
.RI "Class Definition of a private API Country Info\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
