.TH "JMovies.IMDb.Entities.Movies.Genre" 3 "Tue Feb 8 2022" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.Movies.Genre \- Class definition of a genre  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "long \fBID\fP\fC [get, set]\fP"
.br
.RI "Primary Key "
.ti -1c
.RI "string \fBValue\fP\fC [get, set]\fP"
.br
.RI "Name of the \fBGenre\fP "
.ti -1c
.RI "string \fBIdentifier\fP\fC [get, set]\fP"
.br
.RI "Unique identifier of the \fBGenre\fP "
.ti -1c
.RI "long \fBProductionID\fP\fC [get, set]\fP"
.br
.RI "Reference field for \fBProduction\fP "
.in -1c
.SH "Detailed Description"
.PP 
Class definition of a genre 


.SH "Property Documentation"
.PP 
.SS "long JMovies\&.IMDb\&.Entities\&.Movies\&.Genre\&.ID\fC [get]\fP, \fC [set]\fP"

.PP
Primary Key 
.SS "string JMovies\&.IMDb\&.Entities\&.Movies\&.Genre\&.Identifier\fC [get]\fP, \fC [set]\fP"

.PP
Unique identifier of the \fBGenre\fP 
.SS "long JMovies\&.IMDb\&.Entities\&.Movies\&.Genre\&.ProductionID\fC [get]\fP, \fC [set]\fP"

.PP
Reference field for \fBProduction\fP 
.SS "string JMovies\&.IMDb\&.Entities\&.Movies\&.Genre\&.Value\fC [get]\fP, \fC [set]\fP"

.PP
Name of the \fBGenre\fP 

.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
