.TH "JMovies.IMDb.Entities.Common.Image" 3 "Tue Aug 13 2019" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.Common.Image \- Class definition for basic online image  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBTitle\fP\fC [get, set]\fP"
.br
.RI "Title of the image "
.ti -1c
.RI "string \fBURL\fP\fC [get, set]\fP"
.br
.RI "URL of the image "
.in -1c
.SH "Detailed Description"
.PP 
Class definition for basic online image 


.SH "Property Documentation"
.PP 
.SS "string JMovies\&.IMDb\&.Entities\&.Common\&.Image\&.Title\fC [get]\fP, \fC [set]\fP"

.PP
Title of the image 
.SS "string JMovies\&.IMDb\&.Entities\&.Common\&.Image\&.URL\fC [get]\fP, \fC [set]\fP"

.PP
URL of the image 

.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
