.TH "JMovies.IMDb.Entities.Movies.Budget" 3 "Mon Sep 9 2019" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.Movies.Budget \- Class definition of \fBBudget\fP of a Title  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBDescription\fP\fC [get, set]\fP"
.br
.RI "Description related to the budget information "
.ti -1c
.RI "\fBAmount\fP \fBAmount\fP\fC [get, set]\fP"
.br
.RI "Amount of the budget of the title "
.in -1c
.SH "Detailed Description"
.PP 
Class definition of \fBBudget\fP of a Title 


.SH "Property Documentation"
.PP 
.SS "\fBAmount\fP JMovies\&.IMDb\&.Entities\&.Movies\&.Budget\&.Amount\fC [get]\fP, \fC [set]\fP"

.PP
Amount of the budget of the title 
.SS "string JMovies\&.IMDb\&.Entities\&.Movies\&.Budget\&.Description\fC [get]\fP, \fC [set]\fP"

.PP
Description related to the budget information 

.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
