.TH "JMovies.IMDb.Helpers.Movies.SummaryStorylineHelper" 3 "Tue Aug 13 2019" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Helpers.Movies.SummaryStorylineHelper \- Class responsible for parsing the summary-story line section  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBParse\fP (\fBMovie\fP movie, HtmlNode storyLineSection)"
.br
.RI "Method responsible for parsing the summary-story line section 
.br
 "
.in -1c
.SH "Detailed Description"
.PP 
Class responsible for parsing the summary-story line section 


.SH "Member Function Documentation"
.PP 
.SS "static void JMovies\&.IMDb\&.Helpers\&.Movies\&.SummaryStorylineHelper\&.Parse (\fBMovie\fP movie, HtmlNode storyLineSection)\fC [static]\fP"

.PP
Method responsible for parsing the summary-story line section 
.br
 
.PP
\fBParameters\fP
.RS 4
\fImovie\fP Movie instance to be populated
.br
\fIstoryLineSection\fP HTML Node containing Story Line section
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
