.TH "JMovies.IMDb.Tests.Production.ProductionGalleryTests" 3 "Sun Feb 26 2023" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Tests.Production.ProductionGalleryTests \- Test suite for tests related to fetching of the gallery page of the productions\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBFetchingLimitedImages\fP ()"
.br
.RI "Fetches the production data with 5 images\&. "
.ti -1c
.RI "void \fBFetchingWithPagination\fP ()"
.br
.RI "Fetches the production data with 55 images\&. "
.in -1c
.SH "Detailed Description"
.PP 
Test suite for tests related to fetching of the gallery page of the productions\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
