.TH "JMovies.IMDb.Entities.People.Actor" 3 "Tue Feb 8 2022" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.People.Actor \- Class definition of an actor  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBJMovies\&.IMDb\&.Entities\&.People\&.Person\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "override \fBPersonTypeEnum\fP \fBPersonType\fP\fC [get, set]\fP"
.br
.RI "Overriden property of PersonType that returns \fBActor\fP always "
.in -1c
.SH "Detailed Description"
.PP 
Class definition of an actor 


.SH "Property Documentation"
.PP 
.SS "override \fBPersonTypeEnum\fP JMovies\&.IMDb\&.Entities\&.People\&.Actor\&.PersonType\fC [get]\fP, \fC [set]\fP"

.PP
Overriden property of PersonType that returns \fBActor\fP always 

.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
