.TH "JMovies.IMDb.Entities.Settings.BaseDataFetchSettings" 3 "Thu Feb 16 2023" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.Settings.BaseDataFetchSettings \- Base settings class common to both productions and persons\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBJMovies\&.IMDb\&.Entities\&.Settings\&.PersonDataFetchSettings\fP, and \fBJMovies\&.IMDb\&.Entities\&.Settings\&.ProductionDataFetchSettings\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual string \fBPreferredCulture\fP\fC [get, set]\fP"
.br
.RI "Preferred culture for fetching data (where applicable) "
.ti -1c
.RI "virtual bool \fBFetchPrivateData\fP\fC [get, set]\fP"
.br
.RI "Toggles fetching private data available through normally user-click on the website\&. DISCLAIMER: Use this only on private projects\&. Usage of these APIs are not allowed for non-private purposes\&. "
.in -1c
.SH "Detailed Description"
.PP 
Base settings class common to both productions and persons\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
