.TH "JMovies.IMDb.Entities.PrivateAPI.APIData" 3 "Wed Mar 8 2023" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.PrivateAPI.APIData \- Class Definition of a private API Response\&.  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBProductionData\fP \fBProductionData\fP\fC [get, set]\fP"
.br
.RI "Production Data property\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class Definition of a private API Response\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
