.TH "JMovies.IMDb.Entities.Movies.Keyword" 3 "Sun Feb 26 2023" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.Movies.Keyword \- Class definition of a keyword related to a title\&.  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "long \fBID\fP\fC [get, set]\fP"
.br
.RI "Primary Key\&. "
.ti -1c
.RI "string \fBValue\fP\fC [get, set]\fP"
.br
.RI "Keyword name\&. "
.ti -1c
.RI "string \fBIdentifier\fP\fC [get, set]\fP"
.br
.RI "Unique Identifier of a keyword\&. "
.ti -1c
.RI "long \fBProductionID\fP\fC [get, set]\fP"
.br
.RI "Reference field for Production\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class definition of a keyword related to a title\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
