.TH "JMovies.IMDb.Helpers.Movies.SummaryCreditsHelper" 3 "Tue Feb 8 2022" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Helpers.Movies.SummaryCreditsHelper \- Helper class responsible for parsing the summary credits  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBParseCastList\fP (\fBMovie\fP movie, List< \fBCredit\fP > credits, HtmlNode castListNode)"
.br
.RI "Method responsible for parsing the cast list of the movie "
.in -1c
.SH "Detailed Description"
.PP 
Helper class responsible for parsing the summary credits 


.SH "Member Function Documentation"
.PP 
.SS "static void JMovies\&.IMDb\&.Helpers\&.Movies\&.SummaryCreditsHelper\&.ParseCastList (\fBMovie\fP movie, List< \fBCredit\fP > credits, HtmlNode castListNode)\fC [static]\fP"

.PP
Method responsible for parsing the cast list of the movie 
.PP
\fBParameters\fP
.RS 4
\fImovie\fP Movie instance to be populated
.br
\fIcredits\fP Credits list to be filled
.br
\fIcastListNode\fP Html node that holds the cast list
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
