.TH "JMovies.IMDb.Entities.Misc.DataSource" 3 "Wed Dec 15 2021" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.Misc.DataSource \- Class Definition of a data source  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDataSource\fP ()"
.br
.RI "Default constructor of data source "
.ti -1c
.RI "\fBDataSource\fP (\fBDataSourceTypeEnum\fP dataSourceType)"
.br
.RI "Datasource constructor by type "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBID\fP\fC [get, set]\fP"
.br
.RI "Primary key "
.ti -1c
.RI "int \fBIdentifier\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.RI "Name of the source "
.ti -1c
.RI "\fBDataSourceTypeEnum\fP \fBDataSourceType\fP\fC [get, set]\fP"
.br
.RI "Type of the data source "
.in -1c
.SH "Detailed Description"
.PP 
Class Definition of a data source 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "JMovies\&.IMDb\&.Entities\&.Misc\&.DataSource\&.DataSource ()"

.PP
Default constructor of data source 
.SS "JMovies\&.IMDb\&.Entities\&.Misc\&.DataSource\&.DataSource (\fBDataSourceTypeEnum\fP dataSourceType)"

.PP
Datasource constructor by type 
.PP
\fBParameters\fP
.RS 4
\fIdataSourceType\fP 
.RE
.PP

.SH "Property Documentation"
.PP 
.SS "\fBDataSourceTypeEnum\fP JMovies\&.IMDb\&.Entities\&.Misc\&.DataSource\&.DataSourceType\fC [get]\fP, \fC [set]\fP"

.PP
Type of the data source 
.SS "int JMovies\&.IMDb\&.Entities\&.Misc\&.DataSource\&.ID\fC [get]\fP, \fC [set]\fP"

.PP
Primary key 
.SS "int JMovies\&.IMDb\&.Entities\&.Misc\&.DataSource\&.Identifier\fC [get]\fP, \fC [set]\fP"

.PP

.SS "string JMovies\&.IMDb\&.Entities\&.Misc\&.DataSource\&.Name\fC [get]\fP, \fC [set]\fP"

.PP
Name of the source 

.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
