.TH "JMovies.IMDb.Entities.Movies.Language" 3 "Wed Sep 11 2019" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.Movies.Language \- Class definition of a language  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "long \fBID\fP\fC [get, set]\fP"
.br
.RI "Primary Key "
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.RI "Name of the language "
.ti -1c
.RI "string \fBIdentifier\fP\fC [get, set]\fP"
.br
.RI "Unique Identifier of the language "
.in -1c
.SH "Detailed Description"
.PP 
Class definition of a language 


.SH "Property Documentation"
.PP 
.SS "long JMovies\&.IMDb\&.Entities\&.Movies\&.Language\&.ID\fC [get]\fP, \fC [set]\fP"

.PP
Primary Key 
.SS "string JMovies\&.IMDb\&.Entities\&.Movies\&.Language\&.Identifier\fC [get]\fP, \fC [set]\fP"

.PP
Unique Identifier of the language 
.SS "string JMovies\&.IMDb\&.Entities\&.Movies\&.Language\&.Name\fC [get]\fP, \fC [set]\fP"

.PP
Name of the language 

.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
