.TH "JMovies.IMDb.Entities.Movies.TVCharacter" 3 "Sun Feb 26 2023" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.Movies.TVCharacter \- Class definition of a TV Character\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBJMovies\&.IMDb\&.Entities\&.Movies\&.Character\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBEpisodeCount\fP\fC [get, set]\fP"
.br
.RI "Count of episodes the character was in\&. "
.ti -1c
.RI "int? \fBStartYear\fP\fC [get, set]\fP"
.br
.RI "Character first appereance year\&. "
.ti -1c
.RI "int? \fBEndYear\fP\fC [get, set]\fP"
.br
.RI "Character last appereance year\&. "
.ti -1c
.RI "override \fBCharacterTypeEnum\fP \fBCharacterType\fP\fC [get]\fP"
.br
.RI "Overridden character type property to return always TVCharacter\&. "
.in -1c

Properties inherited from \fBJMovies\&.IMDb\&.Entities\&.Movies\&.Character\fP
.in +1c
.ti -1c
.RI "long \fBID\fP\fC [get, set]\fP"
.br
.RI "Primary key of a character\&. "
.ti -1c
.RI "virtual \fBCharacterTypeEnum\fP \fBCharacterType\fP\fC [get, set]\fP"
.br
.RI "Underlining Character Type\&. "
.ti -1c
.RI "long? \fBIMDbID\fP\fC [get, set]\fP"
.br
.RI "IMDb ID\&. "
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.RI "Name of the character\&. "
.ti -1c
.RI "long \fBCreditID\fP\fC [get, set]\fP"
.br
.RI "Reference ID of related credit\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class definition of a TV Character\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
