.TH "JMovies.IMDb.Entities.Settings.Presets.FullProductionDataFetchSettings" 3 "Fri Feb 14 2020" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.Settings.Presets.FullProductionDataFetchSettings \- A preset of data fetch settings that fetches all the data available for productions  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBJMovies\&.IMDb\&.Entities\&.Settings\&.ProductionDataFetchSettings\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBFetchDetailedCast\fP\fC [get]\fP"
.br
.RI "Fetch the detailed cast "
.ti -1c
.RI "override bool \fBFetchImageContents\fP\fC [get]\fP"
.br
.RI "Fetch the image contents "
.ti -1c
.RI "override int \fBMediaImagesFetchCount\fP\fC [get]\fP"
.br
.RI "Fetch all media images "
.ti -1c
.RI "override int \fBCastFetchCount\fP\fC [get]\fP"
.br
.RI "Fetch all cast "
.in -1c
.SH "Detailed Description"
.PP 
A preset of data fetch settings that fetches all the data available for productions 


.SH "Property Documentation"
.PP 
.SS "override int JMovies\&.IMDb\&.Entities\&.Settings\&.Presets\&.FullProductionDataFetchSettings\&.CastFetchCount\fC [get]\fP"

.PP
Fetch all cast 
.SS "override bool JMovies\&.IMDb\&.Entities\&.Settings\&.Presets\&.FullProductionDataFetchSettings\&.FetchDetailedCast\fC [get]\fP"

.PP
Fetch the detailed cast 
.SS "override bool JMovies\&.IMDb\&.Entities\&.Settings\&.Presets\&.FullProductionDataFetchSettings\&.FetchImageContents\fC [get]\fP"

.PP
Fetch the image contents 
.SS "override int JMovies\&.IMDb\&.Entities\&.Settings\&.Presets\&.FullProductionDataFetchSettings\&.MediaImagesFetchCount\fC [get]\fP"

.PP
Fetch all media images 

.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
