.TH "JMovies.IMDb.Helpers.People.PersonPageHelper" 3 "Sun Nov 3 2019" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Helpers.People.PersonPageHelper \- Class responsible for parsing the person page  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBParse\fP (\fBPerson\fP person, HtmlNode documentNode, \fBPersonDataFetchSettings\fP settings)"
.br
.RI "Method responsible for parsing the person page "
.in -1c
.SH "Detailed Description"
.PP 
Class responsible for parsing the person page 


.SH "Member Function Documentation"
.PP 
.SS "static void JMovies\&.IMDb\&.Helpers\&.People\&.PersonPageHelper\&.Parse (\fBPerson\fP person, HtmlNode documentNode, \fBPersonDataFetchSettings\fP settings)\fC [static]\fP"

.PP
Method responsible for parsing the person page 
.PP
\fBParameters\fP
.RS 4
\fIperson\fP Person to be populated
.br
\fIdocumentNode\fP HTML Node containing the person page
.br
\fIsettings\fP Object containing Data Fetch settings
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
