.TH "JMovies.IMDb.Entities.Common.Amount" 3 "Mon Dec 9 2019" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.Common.Amount \- Class definition of Money related Amounts  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "decimal \fBValue\fP\fC [get, set]\fP"
.br
.RI "Decimal value of the amount "
.ti -1c
.RI "string \fBCurrency\fP\fC [get, set]\fP"
.br
.RI "Currency of the amount "
.in -1c
.SH "Detailed Description"
.PP 
Class definition of Money related Amounts 


.SH "Property Documentation"
.PP 
.SS "string JMovies\&.IMDb\&.Entities\&.Common\&.Amount\&.Currency\fC [get]\fP, \fC [set]\fP"

.PP
Currency of the amount 
.SS "decimal JMovies\&.IMDb\&.Entities\&.Common\&.Amount\&.Value\fC [get]\fP, \fC [set]\fP"

.PP
Decimal value of the amount 

.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
