.TH "JMovies.IMDb.Entities.Movies.ActingCredit" 3 "Wed Mar 8 2023" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.Movies.ActingCredit \- Class definition of an Acting Credit\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBJMovies\&.IMDb\&.Entities\&.Movies\&.Credit\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBActingCredit\fP ()"
.br
.RI "Default constructor\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual ICollection< \fBCharacter\fP > \fBCharacters\fP\fC [get, set]\fP"
.br
.RI "Characters played by the actor/actress\&. "
.in -1c

Properties inherited from \fBJMovies\&.IMDb\&.Entities\&.Movies\&.Credit\fP
.in +1c
.ti -1c
.RI "long \fBID\fP\fC [get, set]\fP"
.br
.RI "Primary key\&. "
.ti -1c
.RI "virtual \fBPerson\fP \fBPerson\fP\fC [get, set]\fP"
.br
.RI "Person related to the credit\&. "
.ti -1c
.RI "long \fBPersonID\fP\fC [get, set]\fP"
.br
.RI "Reference id for Person\&. "
.ti -1c
.RI "\fBCreditRoleType\fP \fBRoleType\fP\fC [get, set]\fP"
.br
.RI "Role of the person in the title\&. "
.ti -1c
.RI "long \fBProductionID\fP\fC [get, set]\fP"
.br
.RI "Reference field for Production\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class definition of an Acting Credit\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
