.TH "JMovies.IMDb.Helpers.HttpHelper" 3 "Sun Sep 8 2019" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Helpers.HttpHelper \- Class responsible for providing utility methods for HTTP Operations  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static WebRequest \fBInitializeWebRequest\fP (string url)"
.br
.RI "Initializes the web request using the URL and configures the request for default language and dummy User Agent/IP Info "
.ti -1c
.RI "static Stream \fBGetResponseStream\fP (WebRequest webRequest, int retryCount=0)"
.br
.RI "Retry mechanism for sending Web Request that is required to avoid Connectivity issues "
.in -1c
.SH "Detailed Description"
.PP 
Class responsible for providing utility methods for HTTP Operations 


.SH "Member Function Documentation"
.PP 
.SS "static Stream JMovies\&.IMDb\&.Helpers\&.HttpHelper\&.GetResponseStream (WebRequest webRequest, int retryCount = \fC0\fP)\fC [static]\fP"

.PP
Retry mechanism for sending Web Request that is required to avoid Connectivity issues 
.PP
\fBParameters\fP
.RS 4
\fIwebRequest\fP Request to be sent
.br
\fIretryCount\fP Current Retry Count
.RE
.PP
\fBReturns\fP
.RS 4
Successful Response Stream
.RE
.PP

.SS "static WebRequest JMovies\&.IMDb\&.Helpers\&.HttpHelper\&.InitializeWebRequest (string url)\fC [static]\fP"

.PP
Initializes the web request using the URL and configures the request for default language and dummy User Agent/IP Info 
.PP
\fBParameters\fP
.RS 4
\fIurl\fP URL of the Request
.RE
.PP
\fBReturns\fP
.RS 4
Configured Web Request
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
