.TH "JMovies.IMDb.Entities.Movies.OfficialSite" 3 "Wed Dec 15 2021" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.Movies.OfficialSite \- Class definition of an Official Site  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBTitle\fP\fC [get, set]\fP"
.br
.RI "Title of the official website "
.ti -1c
.RI "string \fBURL\fP\fC [get, set]\fP"
.br
.RI "URL of the official website "
.in -1c
.SH "Detailed Description"
.PP 
Class definition of an Official Site 


.SH "Property Documentation"
.PP 
.SS "string JMovies\&.IMDb\&.Entities\&.Movies\&.OfficialSite\&.Title\fC [get]\fP, \fC [set]\fP"

.PP
Title of the official website 
.SS "string JMovies\&.IMDb\&.Entities\&.Movies\&.OfficialSite\&.URL\fC [get]\fP, \fC [set]\fP"

.PP
URL of the official website 

.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
