.TH "JMovies.IMDb.Tests" 3 "Wed Dec 15 2021" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Tests
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIMDbScrapingTests\fP"
.br
.RI "Test class that provides different test scenarios of \fBIMDb\fP Screen Scraping "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
