.TH "JMovies.IMDb.Helpers.People.PhotoGalleryPageHelper" 3 "Thu Feb 16 2023" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Helpers.People.PhotoGalleryPageHelper \- Class responsible for parsing the Media Images\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBParse\fP (\fBPerson\fP person, string personURL, \fBPersonDataFetchSettings\fP settings)"
.br
.RI "Main Parse method of the Photo Gallery Page\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class responsible for parsing the Media Images\&. 
.SH "Member Function Documentation"
.PP 
.SS "static void JMovies\&.IMDb\&.Helpers\&.People\&.PhotoGalleryPageHelper\&.Parse (\fBPerson\fP person, string personURL, \fBPersonDataFetchSettings\fP settings)\fC [static]\fP"

.PP
Main Parse method of the Photo Gallery Page\&. 
.PP
\fBParameters\fP
.RS 4
\fIperson\fP Person instance that is populated
.br
\fIpersonURL\fP URL of the person page
.br
\fIsettings\fP Object containing Data Fetch settings
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
