.TH "JMovies.IMDb.Entities.Movies.TVCharacter" 3 "Mon Sep 9 2019" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.Movies.TVCharacter \- Class definition of a TV \fBCharacter\fP  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBJMovies\&.IMDb\&.Entities\&.Movies\&.Character\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBEpisodeCount\fP\fC [get, set]\fP"
.br
.RI "Count of episodes the character was in "
.ti -1c
.RI "int? \fBStartYear\fP\fC [get, set]\fP"
.br
.RI "\fBCharacter\fP first appereance year "
.ti -1c
.RI "int? \fBEndYear\fP\fC [get, set]\fP"
.br
.RI "\fBCharacter\fP last appereance year "
.ti -1c
.RI "override \fBCharacterTypeEnum\fP \fBCharacterType\fP\fC [get]\fP"
.br
.RI "Overridden character type property to return always \fBTVCharacter\fP "
.in -1c
.SH "Detailed Description"
.PP 
Class definition of a TV \fBCharacter\fP 


.SH "Property Documentation"
.PP 
.SS "override \fBCharacterTypeEnum\fP JMovies\&.IMDb\&.Entities\&.Movies\&.TVCharacter\&.CharacterType\fC [get]\fP"

.PP
Overridden character type property to return always \fBTVCharacter\fP 
.SS "int? JMovies\&.IMDb\&.Entities\&.Movies\&.TVCharacter\&.EndYear\fC [get]\fP, \fC [set]\fP"

.PP
\fBCharacter\fP last appereance year 
.SS "int JMovies\&.IMDb\&.Entities\&.Movies\&.TVCharacter\&.EpisodeCount\fC [get]\fP, \fC [set]\fP"

.PP
Count of episodes the character was in 
.SS "int? JMovies\&.IMDb\&.Entities\&.Movies\&.TVCharacter\&.StartYear\fC [get]\fP, \fC [set]\fP"

.PP
\fBCharacter\fP first appereance year 

.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
