.TH "JMovies.IMDb.Common.Extensions" 3 "Thu Feb 16 2023" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Common.Extensions
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBaseDataFetchSettingsExtensions\fP"
.br
.RI "Provides extension methods for the BasicDataFetchSettings type of objects\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
