.TH "JMovies.IMDb.Providers.IMDbScraperDataProvider" 3 "Tue Feb 8 2022" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Providers.IMDbScraperDataProvider \- Data provider that fetches the data real-time on \fBIMDb\fP website using Screen Scraping and returns it as per defined in IIMDbDataProvider\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBJMovies\&.IMDb\&.Entities\&.Interfaces\&.IIMDbDataProvider\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProduction\fP \fBGetProduction\fP (long id, \fBProductionDataFetchSettings\fP settings)"
.br
.RI "Gets Production Information iresspective of type "
.ti -1c
.RI "\fBPerson\fP \fBGetPerson\fP (long id, \fBPersonDataFetchSettings\fP settings)"
.br
.RI "Gets Person information "
.ti -1c
.RI "\fBPerson\fP \fBGetPerson\fP (long id, \fBPerson\fP person, \fBPersonDataFetchSettings\fP settings)"
.br
.RI "Gets Person information "
.ti -1c
.RI "\fBMovie\fP \fBGetMovie\fP (long id, \fBProductionDataFetchSettings\fP settings)"
.br
.RI "Gets Movie information "
.ti -1c
.RI "\fBTVSeries\fP \fBGetTvSeries\fP (long id, \fBProductionDataFetchSettings\fP settings)"
.br
.RI "Gets TV Series information "
.ti -1c
.RI "\fBProduction\fP \fBGetProduction\fP (long id)"
.br
.RI "Gets Production Information iresspective of type using the default settings "
.ti -1c
.RI "\fBMovie\fP \fBGetMovie\fP (long id)"
.br
.RI "Gets Movie information using the default settings "
.ti -1c
.RI "\fBTVSeries\fP \fBGetTvSeries\fP (long id)"
.br
.RI "Gets TV Series information using the default settings "
.ti -1c
.RI "\fBPerson\fP \fBGetPerson\fP (long id)"
.br
.RI "Gets Person information using the default settings "
.in -1c
.SH "Detailed Description"
.PP 
Data provider that fetches the data real-time on \fBIMDb\fP website using Screen Scraping and returns it as per defined in IIMDbDataProvider\&. 


.SH "Member Function Documentation"
.PP 
.SS "\fBMovie\fP JMovies\&.IMDb\&.Providers\&.IMDbScraperDataProvider\&.GetMovie (long id)"

.PP
Gets Movie information using the default settings 
.PP
\fBParameters\fP
.RS 4
\fIid\fP ID of the movie
.RE
.PP
\fBReturns\fP
.RS 4
Movie instance containing retreived information
.RE
.PP

.PP
Implements \fBJMovies\&.IMDb\&.Entities\&.Interfaces\&.IIMDbDataProvider\fP\&.
.SS "\fBMovie\fP JMovies\&.IMDb\&.Providers\&.IMDbScraperDataProvider\&.GetMovie (long id, \fBProductionDataFetchSettings\fP settings)"

.PP
Gets Movie information 
.PP
\fBParameters\fP
.RS 4
\fIid\fP ID of the movie
.br
\fIsettings\fP Object containing Data Fetch settings
.RE
.PP
\fBReturns\fP
.RS 4
Movie instance containing retreived information
.RE
.PP

.PP
Implements \fBJMovies\&.IMDb\&.Entities\&.Interfaces\&.IIMDbDataProvider\fP\&.
.SS "\fBPerson\fP JMovies\&.IMDb\&.Providers\&.IMDbScraperDataProvider\&.GetPerson (long id)"

.PP
Gets Person information using the default settings 
.PP
\fBParameters\fP
.RS 4
\fIid\fP ID of the Person
.RE
.PP
\fBReturns\fP
.RS 4
Person instance containing retreived information
.RE
.PP

.PP
Implements \fBJMovies\&.IMDb\&.Entities\&.Interfaces\&.IIMDbDataProvider\fP\&.
.SS "\fBPerson\fP JMovies\&.IMDb\&.Providers\&.IMDbScraperDataProvider\&.GetPerson (long id, \fBPerson\fP person, \fBPersonDataFetchSettings\fP settings)"

.PP
Gets Person information 
.PP
\fBParameters\fP
.RS 4
\fIid\fP ID of the Person
.br
\fIperson\fP Person instance to be populated
.br
\fIsettings\fP Object containing Data Fetch settings
.RE
.PP
\fBReturns\fP
.RS 4
Person instance containing retreived information
.RE
.PP

.SS "\fBPerson\fP JMovies\&.IMDb\&.Providers\&.IMDbScraperDataProvider\&.GetPerson (long id, \fBPersonDataFetchSettings\fP settings)"

.PP
Gets Person information 
.PP
\fBParameters\fP
.RS 4
\fIid\fP ID of the Person
.br
\fIsettings\fP Object containing Data Fetch settings
.RE
.PP
\fBReturns\fP
.RS 4
Person instance containing retreived information
.RE
.PP

.PP
Implements \fBJMovies\&.IMDb\&.Entities\&.Interfaces\&.IIMDbDataProvider\fP\&.
.SS "\fBProduction\fP JMovies\&.IMDb\&.Providers\&.IMDbScraperDataProvider\&.GetProduction (long id)"

.PP
Gets Production Information iresspective of type using the default settings 
.PP
\fBParameters\fP
.RS 4
\fIid\fP ID of the production
.RE
.PP
\fBReturns\fP
.RS 4
Production instance containing retreived information
.RE
.PP

.PP
Implements \fBJMovies\&.IMDb\&.Entities\&.Interfaces\&.IIMDbDataProvider\fP\&.
.SS "\fBProduction\fP JMovies\&.IMDb\&.Providers\&.IMDbScraperDataProvider\&.GetProduction (long id, \fBProductionDataFetchSettings\fP settings)"

.PP
Gets Production Information iresspective of type 
.PP
\fBParameters\fP
.RS 4
\fIid\fP ID of the production
.br
\fIsettings\fP Object containing Data Fetch settings
.RE
.PP
\fBReturns\fP
.RS 4
Production instance containing retreived information
.RE
.PP

.PP
Implements \fBJMovies\&.IMDb\&.Entities\&.Interfaces\&.IIMDbDataProvider\fP\&.
.SS "\fBTVSeries\fP JMovies\&.IMDb\&.Providers\&.IMDbScraperDataProvider\&.GetTvSeries (long id)"

.PP
Gets TV Series information using the default settings 
.PP
\fBParameters\fP
.RS 4
\fIid\fP ID of the TV Series
.RE
.PP
\fBReturns\fP
.RS 4
TV Series instance containing retreived information
.RE
.PP

.PP
Implements \fBJMovies\&.IMDb\&.Entities\&.Interfaces\&.IIMDbDataProvider\fP\&.
.SS "\fBTVSeries\fP JMovies\&.IMDb\&.Providers\&.IMDbScraperDataProvider\&.GetTvSeries (long id, \fBProductionDataFetchSettings\fP settings)"

.PP
Gets TV Series information 
.PP
\fBParameters\fP
.RS 4
\fIid\fP ID of the TV Series
.br
\fIsettings\fP Object containing Data Fetch settings
.RE
.PP
\fBReturns\fP
.RS 4
TV Series instance containing retreived information
.RE
.PP

.PP
Implements \fBJMovies\&.IMDb\&.Entities\&.Interfaces\&.IIMDbDataProvider\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
