.TH "JMovies.IMDb.Entities.Common.Image" 3 "Tue Feb 14 2023" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.Common.Image \- Class definition for basic online image\&.  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "long \fBID\fP\fC [get, set]\fP"
.br
.RI "Primary Key\&. "
.ti -1c
.RI "string \fBTitle\fP\fC [get, set]\fP"
.br
.RI "Title of the image\&. "
.ti -1c
.RI "string \fBURL\fP\fC [get, set]\fP"
.br
.RI "URL of the image\&. "
.ti -1c
.RI "byte[] \fBContent\fP\fC [get, set]\fP"
.br
.RI "Content of the image\&. "
.ti -1c
.RI "long? \fBPersonID\fP\fC [get, set]\fP"
.br
.RI "Related Person ID\&. "
.ti -1c
.RI "long? \fBProductionID\fP\fC [get, set]\fP"
.br
.RI "Related Production ID\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class definition for basic online image\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
