.TH "JMovies.IMDb.Entities.Movies.TVSeries" 3 "Sun Dec 8 2019" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.Movies.TVSeries \- Class definition of TV Series  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBJMovies\&.IMDb\&.Entities\&.Movies\&.Movie\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "override \fBProductionTypeEnum\fP \fBProductionType\fP => \fBProductionTypeEnum\&.TVSeries\fP"
.br
.RI "Type of the production "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int? \fBEndYear\fP\fC [get, set]\fP"
.br
.RI "End Year of the series "
.in -1c
.SH "Detailed Description"
.PP 
Class definition of TV Series 


.SH "Member Data Documentation"
.PP 
.SS "override \fBProductionTypeEnum\fP JMovies\&.IMDb\&.Entities\&.Movies\&.TVSeries\&.ProductionType => \fBProductionTypeEnum\&.TVSeries\fP"

.PP
Type of the production 
.SH "Property Documentation"
.PP 
.SS "int? JMovies\&.IMDb\&.Entities\&.Movies\&.TVSeries\&.EndYear\fC [get]\fP, \fC [set]\fP"

.PP
End Year of the series 

.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
