.TH "JMovies.IMDb.Entities.Movies.ProductionCountry" 3 "Tue Feb 8 2022" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.Movies.ProductionCountry \- Class definition that handles country to production mapping  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "long \fBID\fP\fC [get, set]\fP"
.br
.RI "Primary Key "
.ti -1c
.RI "virtual \fBCountry\fP \fBCountry\fP\fC [get, set]\fP"
.br
.RI "\fBCountry\fP of the production "
.ti -1c
.RI "virtual \fBProduction\fP \fBProduction\fP\fC [get, set]\fP"
.br
.RI "Related \fBProduction\fP "
.ti -1c
.RI "long \fBProductionID\fP\fC [get, set]\fP"
.br
.RI "Reference id of the \fBProduction\fP "
.ti -1c
.RI "long \fBCountryID\fP\fC [get, set]\fP"
.br
.RI "Reference id of the \fBCountry\fP "
.in -1c
.SH "Detailed Description"
.PP 
Class definition that handles country to production mapping 


.SH "Property Documentation"
.PP 
.SS "virtual \fBCountry\fP JMovies\&.IMDb\&.Entities\&.Movies\&.ProductionCountry\&.Country\fC [get]\fP, \fC [set]\fP"

.PP
\fBCountry\fP of the production 
.SS "long JMovies\&.IMDb\&.Entities\&.Movies\&.ProductionCountry\&.CountryID\fC [get]\fP, \fC [set]\fP"

.PP
Reference id of the \fBCountry\fP 
.SS "long JMovies\&.IMDb\&.Entities\&.Movies\&.ProductionCountry\&.ID\fC [get]\fP, \fC [set]\fP"

.PP
Primary Key 
.SS "virtual \fBProduction\fP JMovies\&.IMDb\&.Entities\&.Movies\&.ProductionCountry\&.Production\fC [get]\fP, \fC [set]\fP"

.PP
Related \fBProduction\fP 
.SS "long JMovies\&.IMDb\&.Entities\&.Movies\&.ProductionCountry\&.ProductionID\fC [get]\fP, \fC [set]\fP"

.PP
Reference id of the \fBProduction\fP 

.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
