.TH "JMovies.IMDb.Entities.Movies.LDJson.Info" 3 "Wed Mar 8 2023" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.Movies.LDJson.Info \- Class representing a basic info linked to the production\&.  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBInfoType\fP\fC [get, set]\fP"
.br
.RI "Property representing the info type\&. "
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.RI "Property representing name related to the info\&. "
.ti -1c
.RI "string \fBURL\fP\fC [get, set]\fP"
.br
.RI "Property representing URL related to the info\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class representing a basic info linked to the production\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
