.TH "JMovies.IMDb.Tests.Production.SpecificMoviesTests" 3 "Sun Feb 26 2023" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Tests.Production.SpecificMoviesTests \- Test class that contains the tests which are targeted for specific movies\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBTestMovieThePowerOfTheDog\fP ()"
.br
.RI "Test Method that tests a movie: 'The Power of the Dog'\&. "
.ti -1c
.RI "void \fBTestMovieReadyPlayerOne\fP ()"
.br
.RI "Test Method that tests a movie: 'Ready Player One'\&. "
.ti -1c
.RI "void \fBTestMovieEarwigAndTheWitch\fP ()"
.br
.RI "Test Method that tests a movie: 'Earwig and the Witch'\&. "
.in -1c
.SH "Detailed Description"
.PP 
Test class that contains the tests which are targeted for specific movies\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
