.TH "JMovies.IMDb.Providers" 3 "Thu May 26 2022" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Providers
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIMDbScraperDataProvider\fP"
.br
.RI "Data provider that fetches the data real-time on \fBIMDb\fP website using Screen Scraping and returns it as per defined in IIMDbDataProvider\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
