.TH "JMovies.IMDb.Entities.Misc" 3 "Sun Feb 7 2021" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.Misc
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDataSource\fP"
.br
.RI "Class Definition of a data source "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBDataSourceTypeEnum\fP { \fBDataSourceTypeEnum\&.Undefined\fP, \fBDataSourceTypeEnum\&.IMDb\fP }"
.br
.RI "Class definition of data sources "
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBJMovies\&.IMDb\&.Entities\&.Misc\&.DataSourceTypeEnum\fP\fC [strong]\fP"

.PP
Class definition of data sources 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIUndefined \fP\fP
Default data source 
.TP
\fB\fIIMDb \fP\fP
\fBIMDb\fP as data source 
.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
