.TH "JMovies.IMDb.Tests.Person" 3 "Thu Jul 28 2022" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Tests.Person
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBasicPersonScrapingTests\fP"
.br
.RI "Test class that contains the tests for basic scraping scenarios for persons "
.ti -1c
.RI "class \fBPersonAsyncTests\fP"
.br
.RI "Test suite designed to test asnyc operations "
.ti -1c
.RI "class \fBPersonGalleryTests\fP"
.br
.RI "Test suite for tests related to fetching of the gallery page of the persons "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
