.TH "JMovies.IMDb.Entities.Movies.Country" 3 "Wed Mar 8 2023" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.Movies.Country \- Class definition of a country\&.  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "long \fBID\fP\fC [get, set]\fP"
.br
.RI "Primary Key\&. "
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.RI "Name of the country\&. "
.ti -1c
.RI "string \fBIdentifier\fP\fC [get, set]\fP"
.br
.RI "Unique identifier of the country\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class definition of a country\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
