.TH "JMovies.IMDb.Common.Constants.GeneralRegexConstants" 3 "Thu Jul 28 2022" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Common.Constants.GeneralRegexConstants \- Class responsible for holding the Regex definitions that are commonly used  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly Regex \fBAmountStringRegex\fP = new Regex(@'^([^a\-zA\-Z0\-9_\\s\\n]*\\s?|[a\-zA\-Z]{2,3}\\s?)([\\d\\\&.,]+)(\\s?[^a\-zA\-Z0\-9_\\s\\n]*|\\s?[a\-zA\-Z]{2,3})$', RegexOptions\&.Multiline)"
.br
.RI "Regex that captures any money string "
.ti -1c
.RI "static readonly Regex \fBPharantesisRegex\fP = new Regex(@'\\((\&.+)\\)')"
.br
.RI "Basic Regex that captures text inside pharantesis "
.ti -1c
.RI "static readonly Regex \fBHtmlDatetimeTagRegex\fP = new Regex(@'PT(\\d*D)?(\\d*H)?(\\d*M)?(\\d*S)?')"
.br
.RI "Regex that captures and groups the HTML Datetime attribute details "
.ti -1c
.RI "static readonly Regex \fBAllNumericRegex\fP = new Regex(@'^(\\d+)$')"
.br
.RI "Regex that captures all numeric strings "
.in -1c
.SH "Detailed Description"
.PP 
Class responsible for holding the Regex definitions that are commonly used 


.SH "Member Data Documentation"
.PP 
.SS "readonly Regex JMovies\&.IMDb\&.Common\&.Constants\&.GeneralRegexConstants\&.AllNumericRegex = new Regex(@'^(\\d+)$')\fC [static]\fP"

.PP
Regex that captures all numeric strings 
.SS "readonly Regex JMovies\&.IMDb\&.Common\&.Constants\&.GeneralRegexConstants\&.AmountStringRegex = new Regex(@'^([^a\-zA\-Z0\-9_\\s\\n]*\\s?|[a\-zA\-Z]{2,3}\\s?)([\\d\\\&.,]+)(\\s?[^a\-zA\-Z0\-9_\\s\\n]*|\\s?[a\-zA\-Z]{2,3})$', RegexOptions\&.Multiline)\fC [static]\fP"

.PP
Regex that captures any money string 
.SS "readonly Regex JMovies\&.IMDb\&.Common\&.Constants\&.GeneralRegexConstants\&.HtmlDatetimeTagRegex = new Regex(@'PT(\\d*D)?(\\d*H)?(\\d*M)?(\\d*S)?')\fC [static]\fP"

.PP
Regex that captures and groups the HTML Datetime attribute details 
.SS "readonly Regex JMovies\&.IMDb\&.Common\&.Constants\&.GeneralRegexConstants\&.PharantesisRegex = new Regex(@'\\((\&.+)\\)')\fC [static]\fP"

.PP
Basic Regex that captures text inside pharantesis 

.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
