.TH "JMovies.IMDb.Entities.Common.Length" 3 "Thu Feb 16 2023" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.Common.Length \- Class definition of Length that contains both Imperial and Metric length information\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLength\fP ()"
.br
.RI "Default empty constructor\&. "
.ti -1c
.RI "\fBLength\fP (int metricLength)"
.br
.RI "Metric based Length constructor\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBMetric\fP\fC [get, set]\fP"
.br
.RI "Metric Length\&. "
.ti -1c
.RI "double \fBImperial\fP\fC [get]\fP"
.br
.RI "Imperial Length\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class definition of Length that contains both Imperial and Metric length information\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "JMovies\&.IMDb\&.Entities\&.Common\&.Length\&.Length (int metricLength)"

.PP
Metric based Length constructor\&. 
.PP
\fBParameters\fP
.RS 4
\fImetricLength\fP Metric length
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
