.TH "JMovies.IMDb.Entities.Movies.AKA" 3 "Tue Aug 13 2019" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.Movies.AKA \- Class definition for other names of the title  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBDescription\fP\fC [get, set]\fP"
.br
.RI "Description of the alternative name "
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.RI "Alternative name of the Title "
.in -1c
.SH "Detailed Description"
.PP 
Class definition for other names of the title 


.SH "Property Documentation"
.PP 
.SS "string JMovies\&.IMDb\&.Entities\&.Movies\&.AKA\&.Description\fC [get]\fP, \fC [set]\fP"

.PP
Description of the alternative name 
.SS "string JMovies\&.IMDb\&.Entities\&.Movies\&.AKA\&.Name\fC [get]\fP, \fC [set]\fP"

.PP
Alternative name of the Title 

.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
