.TH "JMovies.IMDb.Tests.IMDbScrapingTests" 3 "Sun Feb 7 2021" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Tests.IMDbScrapingTests \- Test class that provides different test scenarios of \fBIMDb\fP Screen Scraping  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBProductionScraping\fP ()"
.br
.RI "Method that tests scraping of different Production Details for basic details "
.ti -1c
.RI "void \fBDetailedProductionScraping\fP ()"
.br
.RI "Method that tests scraping of different Production Details for extended details "
.ti -1c
.RI "void \fBPersonScraping\fP ()"
.br
.RI "Method that tests scraping of person pages "
.ti -1c
.RI "void \fBDetailedPersonScraping\fP ()"
.br
.RI "Method that tests detailed scraping of person pages "
.ti -1c
.RI "void \fBTVShowWithNoEndTest\fP ()"
.br
.RI "Test Method that tests a production with start date but no end date "
.in -1c
.SH "Detailed Description"
.PP 
Test class that provides different test scenarios of \fBIMDb\fP Screen Scraping 


.SH "Member Function Documentation"
.PP 
.SS "void JMovies\&.IMDb\&.Tests\&.IMDbScrapingTests\&.DetailedPersonScraping ()"

.PP
Method that tests detailed scraping of person pages 
.SS "void JMovies\&.IMDb\&.Tests\&.IMDbScrapingTests\&.DetailedProductionScraping ()"

.PP
Method that tests scraping of different Production Details for extended details 
.SS "void JMovies\&.IMDb\&.Tests\&.IMDbScrapingTests\&.PersonScraping ()"

.PP
Method that tests scraping of person pages 
.SS "void JMovies\&.IMDb\&.Tests\&.IMDbScrapingTests\&.ProductionScraping ()"

.PP
Method that tests scraping of different Production Details for basic details 
.SS "void JMovies\&.IMDb\&.Tests\&.IMDbScrapingTests\&.TVShowWithNoEndTest ()"

.PP
Test Method that tests a production with start date but no end date 

.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
