.TH "JMovies.IMDb.Entities.Settings.Presets" 3 "Sat Sep 14 2019" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.Settings.Presets
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBasicPersonDataFetchSettings\fP"
.br
.RI "A preset of settings to fetch only basic person data "
.ti -1c
.RI "class \fBBasicProductionDataFetchSettings\fP"
.br
.RI "A preset of settings to fetch only basic production data "
.ti -1c
.RI "class \fBFullPersonDataFetchSettings\fP"
.br
.RI "A preset of data fetch settings that fetches all the data available for persons "
.ti -1c
.RI "class \fBFullProductionDataFetchSettings\fP"
.br
.RI "A preset of data fetch settings that fetches all the data available for productions "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
