.TH "JMovies.IMDb.Entities.Interfaces.IIMDbDataProvider" 3 "Thu Jul 28 2022" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.Interfaces.IIMDbDataProvider \- Data provider interface that Scraper implements\&. This interface can be safely used for Dependency Injection\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBJMovies\&.IMDb\&.Providers\&.IMDbScraperDataProvider\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProduction\fP \fBGetProduction\fP (long id)"
.br
.RI "Gets Production Information iresspective of type using the default settings "
.ti -1c
.RI "Task< \fBProduction\fP > \fBGetProductionAsync\fP (long id)"
.br
.RI "Gets Production Information iresspective of type using the default settings "
.ti -1c
.RI "\fBMovie\fP \fBGetMovie\fP (long id)"
.br
.RI "Gets Movie information using the default settings "
.ti -1c
.RI "Task< \fBMovie\fP > \fBGetMovieAsync\fP (long id)"
.br
.RI "Gets Movie information using the default settings "
.ti -1c
.RI "\fBTVSeries\fP \fBGetTvSeries\fP (long id)"
.br
.RI "Gets TV Series information using the default settings "
.ti -1c
.RI "Task< \fBTVSeries\fP > \fBGetTvSeriesAsync\fP (long id)"
.br
.RI "Gets TV Series information using the default settings "
.ti -1c
.RI "\fBProduction\fP \fBGetProduction\fP (long id, \fBProductionDataFetchSettings\fP settings)"
.br
.RI "Gets Production Information iresspective of type "
.ti -1c
.RI "Task< \fBProduction\fP > \fBGetProductionAsync\fP (long id, \fBProductionDataFetchSettings\fP settings)"
.br
.RI "Gets Production Information iresspective of type "
.ti -1c
.RI "\fBMovie\fP \fBGetMovie\fP (long id, \fBProductionDataFetchSettings\fP settings)"
.br
.RI "Gets Movie information "
.ti -1c
.RI "Task< \fBMovie\fP > \fBGetMovieAsync\fP (long id, \fBProductionDataFetchSettings\fP settings)"
.br
.RI "Gets Movie information "
.ti -1c
.RI "\fBTVSeries\fP \fBGetTvSeries\fP (long id, \fBProductionDataFetchSettings\fP settings)"
.br
.RI "Gets TV Series information "
.ti -1c
.RI "Task< \fBTVSeries\fP > \fBGetTvSeriesAsync\fP (long id, \fBProductionDataFetchSettings\fP settings)"
.br
.RI "Gets TV Series information "
.ti -1c
.RI "\fBPerson\fP \fBGetPerson\fP (long id, \fBPersonDataFetchSettings\fP settings)"
.br
.RI "Gets Person information "
.ti -1c
.RI "Task< \fBPerson\fP > \fBGetPersonAsync\fP (long id, \fBPersonDataFetchSettings\fP settings)"
.br
.RI "Gets Person information "
.ti -1c
.RI "\fBPerson\fP \fBGetPerson\fP (long id)"
.br
.RI "Gets Person information using the default settings "
.ti -1c
.RI "Task< \fBPerson\fP > \fBGetPersonAsync\fP (long id)"
.br
.RI "Gets Person information using the default settings "
.in -1c
.SH "Detailed Description"
.PP 
Data provider interface that Scraper implements\&. This interface can be safely used for Dependency Injection\&. 


.SH "Member Function Documentation"
.PP 
.SS "\fBMovie\fP JMovies\&.IMDb\&.Entities\&.Interfaces\&.IIMDbDataProvider\&.GetMovie (long id)"

.PP
Gets Movie information using the default settings 
.PP
\fBParameters\fP
.RS 4
\fIid\fP ID of the movie
.RE
.PP
\fBReturns\fP
.RS 4
Movie instance containing retreived information
.RE
.PP

.PP
Implemented in \fBJMovies\&.IMDb\&.Providers\&.IMDbScraperDataProvider\fP\&.
.SS "\fBMovie\fP JMovies\&.IMDb\&.Entities\&.Interfaces\&.IIMDbDataProvider\&.GetMovie (long id, \fBProductionDataFetchSettings\fP settings)"

.PP
Gets Movie information 
.PP
\fBParameters\fP
.RS 4
\fIid\fP ID of the movie
.br
\fIsettings\fP Object containing Data Fetch settings
.RE
.PP
\fBReturns\fP
.RS 4
Movie instance containing retreived information
.RE
.PP

.PP
Implemented in \fBJMovies\&.IMDb\&.Providers\&.IMDbScraperDataProvider\fP\&.
.SS "Task<\fBMovie\fP> JMovies\&.IMDb\&.Entities\&.Interfaces\&.IIMDbDataProvider\&.GetMovieAsync (long id)"

.PP
Gets Movie information using the default settings 
.PP
\fBParameters\fP
.RS 4
\fIid\fP ID of the movie
.RE
.PP
\fBReturns\fP
.RS 4
Task that fetches Movie instance containing retreived information
.RE
.PP

.PP
Implemented in \fBJMovies\&.IMDb\&.Providers\&.IMDbScraperDataProvider\fP\&.
.SS "Task<\fBMovie\fP> JMovies\&.IMDb\&.Entities\&.Interfaces\&.IIMDbDataProvider\&.GetMovieAsync (long id, \fBProductionDataFetchSettings\fP settings)"

.PP
Gets Movie information 
.PP
\fBParameters\fP
.RS 4
\fIid\fP ID of the movie
.br
\fIsettings\fP Object containing Data Fetch settings
.RE
.PP
\fBReturns\fP
.RS 4
Taks that fetches Movie instance containing retreived information
.RE
.PP

.PP
Implemented in \fBJMovies\&.IMDb\&.Providers\&.IMDbScraperDataProvider\fP\&.
.SS "\fBPerson\fP JMovies\&.IMDb\&.Entities\&.Interfaces\&.IIMDbDataProvider\&.GetPerson (long id)"

.PP
Gets Person information using the default settings 
.PP
\fBParameters\fP
.RS 4
\fIid\fP ID of the Person
.RE
.PP
\fBReturns\fP
.RS 4
Person instance containing retreived information
.RE
.PP

.PP
Implemented in \fBJMovies\&.IMDb\&.Providers\&.IMDbScraperDataProvider\fP\&.
.SS "\fBPerson\fP JMovies\&.IMDb\&.Entities\&.Interfaces\&.IIMDbDataProvider\&.GetPerson (long id, \fBPersonDataFetchSettings\fP settings)"

.PP
Gets Person information 
.PP
\fBParameters\fP
.RS 4
\fIid\fP ID of the Person
.br
\fIsettings\fP Object containing Data Fetch settings
.RE
.PP
\fBReturns\fP
.RS 4
Person instance containing retreived information
.RE
.PP

.PP
Implemented in \fBJMovies\&.IMDb\&.Providers\&.IMDbScraperDataProvider\fP\&.
.SS "Task<\fBPerson\fP> JMovies\&.IMDb\&.Entities\&.Interfaces\&.IIMDbDataProvider\&.GetPersonAsync (long id)"

.PP
Gets Person information using the default settings 
.PP
\fBParameters\fP
.RS 4
\fIid\fP ID of the Person
.RE
.PP
\fBReturns\fP
.RS 4
Task that fetches the Person instance containing retreived information
.RE
.PP

.PP
Implemented in \fBJMovies\&.IMDb\&.Providers\&.IMDbScraperDataProvider\fP\&.
.SS "Task<\fBPerson\fP> JMovies\&.IMDb\&.Entities\&.Interfaces\&.IIMDbDataProvider\&.GetPersonAsync (long id, \fBPersonDataFetchSettings\fP settings)"

.PP
Gets Person information 
.PP
\fBParameters\fP
.RS 4
\fIid\fP ID of the Person
.br
\fIsettings\fP Object containing Data Fetch settings
.RE
.PP
\fBReturns\fP
.RS 4
Task that fetches Person instance containing retreived information
.RE
.PP

.PP
Implemented in \fBJMovies\&.IMDb\&.Providers\&.IMDbScraperDataProvider\fP\&.
.SS "\fBProduction\fP JMovies\&.IMDb\&.Entities\&.Interfaces\&.IIMDbDataProvider\&.GetProduction (long id)"

.PP
Gets Production Information iresspective of type using the default settings 
.PP
\fBParameters\fP
.RS 4
\fIid\fP ID of the production
.RE
.PP
\fBReturns\fP
.RS 4
Production instance containing retreived information
.RE
.PP

.PP
Implemented in \fBJMovies\&.IMDb\&.Providers\&.IMDbScraperDataProvider\fP\&.
.SS "\fBProduction\fP JMovies\&.IMDb\&.Entities\&.Interfaces\&.IIMDbDataProvider\&.GetProduction (long id, \fBProductionDataFetchSettings\fP settings)"

.PP
Gets Production Information iresspective of type 
.PP
\fBParameters\fP
.RS 4
\fIid\fP ID of the production
.br
\fIsettings\fP Object containing Data Fetch settings
.RE
.PP
\fBReturns\fP
.RS 4
Production instance containing retreived information
.RE
.PP

.PP
Implemented in \fBJMovies\&.IMDb\&.Providers\&.IMDbScraperDataProvider\fP\&.
.SS "Task<\fBProduction\fP> JMovies\&.IMDb\&.Entities\&.Interfaces\&.IIMDbDataProvider\&.GetProductionAsync (long id)"

.PP
Gets Production Information iresspective of type using the default settings 
.PP
\fBParameters\fP
.RS 4
\fIid\fP ID of the production
.RE
.PP
\fBReturns\fP
.RS 4
Task that fetches Production instance containing retreived information
.RE
.PP

.PP
Implemented in \fBJMovies\&.IMDb\&.Providers\&.IMDbScraperDataProvider\fP\&.
.SS "Task<\fBProduction\fP> JMovies\&.IMDb\&.Entities\&.Interfaces\&.IIMDbDataProvider\&.GetProductionAsync (long id, \fBProductionDataFetchSettings\fP settings)"

.PP
Gets Production Information iresspective of type 
.PP
\fBParameters\fP
.RS 4
\fIid\fP ID of the production
.br
\fIsettings\fP Object containing Data Fetch settings
.RE
.PP
\fBReturns\fP
.RS 4
Task that fetches Production instance containing retreived information
.RE
.PP

.PP
Implemented in \fBJMovies\&.IMDb\&.Providers\&.IMDbScraperDataProvider\fP\&.
.SS "\fBTVSeries\fP JMovies\&.IMDb\&.Entities\&.Interfaces\&.IIMDbDataProvider\&.GetTvSeries (long id)"

.PP
Gets TV Series information using the default settings 
.PP
\fBParameters\fP
.RS 4
\fIid\fP ID of the TV Series
.RE
.PP
\fBReturns\fP
.RS 4
TV Series instance containing retreived information
.RE
.PP

.SS "\fBTVSeries\fP JMovies\&.IMDb\&.Entities\&.Interfaces\&.IIMDbDataProvider\&.GetTvSeries (long id, \fBProductionDataFetchSettings\fP settings)"

.PP
Gets TV Series information 
.PP
\fBParameters\fP
.RS 4
\fIid\fP ID of the TV Series
.br
\fIsettings\fP Object containing Data Fetch settings
.RE
.PP
\fBReturns\fP
.RS 4
TV Series instance containing retreived information
.RE
.PP

.PP
Implemented in \fBJMovies\&.IMDb\&.Providers\&.IMDbScraperDataProvider\fP\&.
.SS "Task<\fBTVSeries\fP> JMovies\&.IMDb\&.Entities\&.Interfaces\&.IIMDbDataProvider\&.GetTvSeriesAsync (long id)"

.PP
Gets TV Series information using the default settings 
.PP
\fBParameters\fP
.RS 4
\fIid\fP ID of the TV Series
.RE
.PP
\fBReturns\fP
.RS 4
Task that fetches TV Series instance containing retreived information
.RE
.PP

.PP
Implemented in \fBJMovies\&.IMDb\&.Providers\&.IMDbScraperDataProvider\fP\&.
.SS "Task<\fBTVSeries\fP> JMovies\&.IMDb\&.Entities\&.Interfaces\&.IIMDbDataProvider\&.GetTvSeriesAsync (long id, \fBProductionDataFetchSettings\fP settings)"

.PP
Gets TV Series information 
.PP
\fBParameters\fP
.RS 4
\fIid\fP ID of the TV Series
.br
\fIsettings\fP Object containing Data Fetch settings
.RE
.PP
\fBReturns\fP
.RS 4
Task that fetches TV Series instance containing retreived information
.RE
.PP

.PP
Implemented in \fBJMovies\&.IMDb\&.Providers\&.IMDbScraperDataProvider\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
