.TH "JMovies.IMDb.Entities.Common.Length" 3 "Wed Dec 15 2021" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Entities.Common.Length \- Class definition of \fBLength\fP that contains both Imperial and Metric length information  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLength\fP ()"
.br
.RI "Default empty constructor "
.ti -1c
.RI "\fBLength\fP (int metricLength)"
.br
.RI "Metric based \fBLength\fP constructor "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBMetric\fP\fC [get, set]\fP"
.br
.RI "Metric \fBLength\fP "
.ti -1c
.RI "double \fBImperial\fP\fC [get]\fP"
.br
.RI "Imperial \fBLength\fP "
.in -1c
.SH "Detailed Description"
.PP 
Class definition of \fBLength\fP that contains both Imperial and Metric length information 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "JMovies\&.IMDb\&.Entities\&.Common\&.Length\&.Length ()"

.PP
Default empty constructor 
.SS "JMovies\&.IMDb\&.Entities\&.Common\&.Length\&.Length (int metricLength)"

.PP
Metric based \fBLength\fP constructor 
.PP
\fBParameters\fP
.RS 4
\fImetricLength\fP Metric length
.RE
.PP

.SH "Property Documentation"
.PP 
.SS "double JMovies\&.IMDb\&.Entities\&.Common\&.Length\&.Imperial\fC [get]\fP"

.PP
Imperial \fBLength\fP 
.SS "int JMovies\&.IMDb\&.Entities\&.Common\&.Length\&.Metric\fC [get]\fP, \fC [set]\fP"

.PP
Metric \fBLength\fP 

.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
