.TH "JMovies.IMDb.Helpers.HtmlHelper" 3 "Wed Mar 8 2023" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Helpers.HtmlHelper \- Class responsible for providing utility methods related to HTML related operations\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static HtmlDocument \fBGetNewHtmlDocument\fP ()"
.br
.RI "Method responsible to initialize and configure a new Html Document\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class responsible for providing utility methods related to HTML related operations\&. 
.SH "Member Function Documentation"
.PP 
.SS "static HtmlDocument JMovies\&.IMDb\&.Helpers\&.HtmlHelper\&.GetNewHtmlDocument ()\fC [static]\fP"

.PP
Method responsible to initialize and configure a new Html Document\&. 
.PP
\fBReturns\fP
.RS 4
Initialized and configured HtmlDocument instance
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
