.TH "JMovies.IMDb.Tests.Production.BasicProductionScrapingTests" 3 "Sun Feb 26 2023" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMovies.IMDb.Tests.Production.BasicProductionScrapingTests \- Test class that contains the tests for basic scraping scenarios for productions\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBProductionScraping\fP ()"
.br
.RI "Method that tests scraping of different Production Details for basic details\&. "
.ti -1c
.RI "void \fBDetailedProductionScraping\fP ()"
.br
.RI "Method that tests scraping of different Production Details for extended details\&. "
.in -1c
.SH "Detailed Description"
.PP 
Test class that contains the tests for basic scraping scenarios for productions\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for JMovies\&.IMDb from the source code\&.
