.TH "md__r_e_a_d_m_e" 3 "Sun Nov 3 2019" "JMovies.IMDb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__r_e_a_d_m_e \- \fBJMovies\&.IMDb\fP 

.SS "JMovies IMDb Data Provider Library"
\fC\fP  
.PP
A IMDb data provider library written for \&.NET Standart platform that uses screen scraping to gather the data from IMDb on demand\&.
.SH "Under the hood"
.PP
\fBJMovies\&.IMDb\fP uses \&.NET standart Http Web Requests to fetch the IMDB pages and parse them using HtmlAgilityPack+Fizzler\&.
.SH "Maintenance"
.PP
I will personaly maintain the project as much as i can but as it uses Screen Scraping it is possible that it will require some changes along the way, so every issue report and pull request is welcome!
.SH "Code Documentation"
.PP
Documentation website can be found under \fCJMovies\&.IMDb GitHub Pages\fP\&.
.SH "Warning"
.PP
Please know that this library is not intended for bulk data scraping from IMDb and it is restricted by them\&. Also note that this library is not affliated with IMDB and you need to use it at your own risk/responsibility\&. 
